### PR TITLE
Fix Storybook TypeScript errors

### PR DESCRIPTION
**Pull request by jecassis**
When testing a different pull request, I encountered Storybook build failures due to TypeScript errors.

#### What does this PR do?
This pull request clears the errors and allows the build to finish and Storybook to be available in the browser. The errors are cleared by initializing `useState()` to something other than `undefined`.

#### Where should the reviewer start?
The `useState()` initialization in each of these files:

- `src/js/components/List/stories/typescript/selected.tsx`
- `src/js/components/Meter/stories/typescript/MultipleValues.tsx`
- `src/js/components/Tabs/stories/typescript/Controlled.tsx`

#### What testing has been done on this PR?
Storybook builds and components function as expected in the browser.

#### How should this be manually tested?
Storybook builds and List, Meter, and Tabs function in the browser.

#### Any background context you want to provide?
None.

#### What are the relevant issues?
None at the moment.

#### Screenshots (if appropriate)
Not available.

#### Do the grommet docs need to be updated?
No.

#### Should this PR be mentioned in the release notes?
No preference.

#### Is this change backwards compatible or is it a breaking change?
Not applicable.

### CODE REVIEW

**Comment by ShimiSun** [comment]
What may be the reason I'm not experiencing those errors on my end?

**Comment by jecassis** [comment]
Honestly, I'm not familiar enough with TypeScript to give you a good answer. The errors were blocking on my end to test PR #3843 manually using Storybook. So I worked around them and these are those workarounds. CI seems unaffected in either PR as well.

For reference, this was encountered on Windows 10 1909 with TypeScript 3.7.5.

**Comment by ShimiSun** [comment]
Thanks, I tested it locally and it looks good.
Wondering how come we didn't catch it sooner, @dallas any thoughts?

**Comment by dallas** [comment]
Not sure. It definitely seems like TypeScript should complain for everybody in regards to these implicit `undefined` values (without setting up any type expectations). It could be the version of `@types/react` that got installed or even the version of Storybook (or some version of Storybook’s dependencies) that’s complaining for @jecassis but isn’t complaining for you locally, or me locally, or in GitHub automated builds and whatnot.

**Pull request merged**
