### PR TITLE
Use string method supported in ie11 (closes #3221)

### LINKED ISSUE #3221: Layer component error in IE11
The layer component uses the `String.prototype.includes` method, which is not available in IE11: 

https://github.com/grommet/grommet/blob/master/src/js/components/Layer/StyledLayer.js#L79

Since no polyfill is included, this obviously results in an error being thrown immediately in that browser when the component is used.

### PR DESCRIPTION
**Pull request by stefk**
Signed-off-by: Stéphane Klein <stephaneklein221@gmail.com>

#### What does this PR do?

It fixes ie11 compatibilty for the layer component.

#### What testing has been done on this PR?

Automated tests.

#### What are the relevant issues?

#3221 

#### Do the grommet docs need to be updated?

No.

#### Should this PR be mentioned in the release notes?

Not sure.

#### Is this change backwards compatible or is it a breaking change?

It's backwards compatible.

### CODE REVIEW

**Comment by ShimiSun** [comment]
@stefk thank you for following up with a PR!!
will you be able to share the markup code that reproduced the problem of Layer on IE?

**Comment by stefk** [comment]
@ShimiSun, the error is thrown as soon as the Layer component is rendered, so the problem can be reproduced with this minimal code:

```jsx
import React from "react";
import ReactDOM from "react-dom";
import { Layer } from "grommet";

ReactDOM.render(<Layer/>, document.body);
````

This probably deserves an separate issue, but I also noticed that the grommet website is broken in ie 11 (some vendor code contains un-transpiled arrow functions).

**Comment by ShimiSun** [comment]
@stefk yea, thanks for pointing it out, if you have any insights on it, feel free to share your comments https://github.com/grommet/grommet/issues/3164

**Comment by stefk** [comment]
I took some time to debug the website as well: https://github.com/grommet/grommet-site/pull/110.

(and now I'm done with ie11 for at least one year ;))

**Comment by crashuniverse** [comment]
Note to self: There are 6 more occurrence of `.includes` that I'd like to create an issue for. This can help us fix such compatibility problems before anyone faces them on IE11 as we can use this nice approach suggested in this PR everywhere else too (carefully).

**Comment by ShimiSun** [comment]
Thank you again for filling this PR buddy! I wasn't able to reproduce the problem while using storybook's Layer for some reason 🤔,  but I was able to reproduce it on a non-grommet-core project (standalone) that used the markup you shared on the top - so Thank You - the markup was helpful!
Screen Shot 2019-07-30 at 3 18 25 PM

The issue and errors were gone after building and linking your code to the standalone project 💯 
Kudos to you my friend, and thank you for taking the time to make a contribution!

@crashuniverse thank you for the investigation, I extracted your comment to a new issue #3234.

**Comment by stefk** [comment]
You're welcome ;)

> I wasn't able to reproduce the problem while using storybook's Layer for some reason 🤔

That's because there's already a polyfill for that method included in the storybook app (I think it comes from [here]( https://github.com/storybookjs/storybook/blob/3ca95c44bced0ba66aedff53a9a492c9b9e1bffd/lib/core/src/server/common/polyfills.js#L2)).

**Comment by ShimiSun** [comment]
@stefk thanks for sharing your further findings!!
I gotta ask a question, I'm trying to understand the reason users still use IE11, my guess is that their company's browser-support is limited. Is it true for your case as well?

**Comment by crashuniverse** [comment]
I once worked in one of the big four banks. They had hundreds of web applications accessible via web browsers only. The IT team was distributed, very knowledgeable and offered Chrome as an approved installable software. In 2013 they were trying to phase out IE6 completely that involved making every software work on the new versions increasing the scope of change exponentially, collaborating with authors, third party companies etc. In presence of an old browser, a lot of people use it for everything. Unless you remove it from their computers.

**Comment by stefk** [comment]
@ShimiSun given the product we're developing and our demographics, I'd say it's unlikely our IE users are limited by the policy of their company. Like @crashuniverse, I believe the main problem is the force of habit. Some people just don't care about new software and don't want to be bothered ^^.

**Pull request merged**
