### PR TITLE
New Proposed Carrot icon.

### PR DESCRIPTION
**Pull request by mtgibbs**
Updated Carrot icons to better represent the visualization of a carrot.

### CODE REVIEW

**Comment by alansouzati** [comment]
@L0ZZI would you mind taking a look at this ?

**Comment by bryanjacquot** [comment]
Thanks for the contribution @mtgibbs.  However, I believe the suggested icon is a bit too literal.  I'll leave it to @L0ZZI but I don't believe this fits with the brand's design language.

**Comment by mtgibbs** [comment]
https://github.com/grommet/grommet/pull/236

**Comment by bryanjacquot** [comment]
Ha ha, I get it.  I mentioned in our daily standup that I was wondering if this was a joke.  :-)

**Comment by mtgibbs** [comment]
I was just making sure that the real PR didn't get overlooked because of the silly one.  I'm going to close this now.

**Pull request closed without merging**
