### PR TITLE
removed modal from center layer example

### PR DESCRIPTION
**Pull request by IanKBovard**
#### What does this PR do?
Changes the center layer example to its original version, by removing modal from both layers.

#### Where should the reviewer start?
Layer stories center.js

#### Any background context you want to provide?
This was a change that was never meant to be pushed. Was testing an issue, and forgot to revert my changes.

#### What are the relevant issues?
None
#### Do the grommet docs need to be updated?
No
#### Should this PR be mentioned in the release notes?
No
#### Is this change backwards compatible or is it a breaking change?
Yes

### CODE REVIEW

**Comment by ShimiSun** [comment]
Can you revert all the files that are not related to the story?

**Comment by IanKBovard** [comment]
removed the files

**Comment by ShimiSun** [comment]
Are you sure? I'm still seeing 5 file changes, it should be just one.

**Comment by IanKBovard** [comment]
ill close this and make a new pr without the files.

**Pull request closed without merging**
