### PR TITLE
Added hoverOverlay property to Chart Legend

### LINKED ISSUE #360: Add hover property to Chart Legend
When using the overlay legend position the legend is always docked to the important property when the chart first loads.  This blocks the initial view of chart data points.  Due to this we should add a property to the legend called hoverOverlay that only shows the chart legend when the data points are hovered.

### PR DESCRIPTION
**Pull request by elronalds**
Fixes #360

### CODE REVIEW

**Comment by alansouzati** [comment]
Thanks for your contribution. 

I was looking into your PR and I faced issues when rendering Charts without legends. I believe this line is causing the issue:

```javascript
this.props.legend.hoverOnly
```

As legend is not always there it fails here.

In general, I think we can fix without the need for `hoverOnly`. If you look in here: 

https://github.com/grommet/grommet/blob/master/src/js/components/Chart.js#L312

You can see that we will always set the `defaultXIndex` to 0 if `this.props.series` is present. As we always have series for Chart, defaultXIndex is 0, instead of -1. The only case defaultXIndex is -1 is the loading scenario for Charts.

So, I propose we remove this block if we want the default index to be -1. There are some other places in this code that we will need to change to support defaultXIndex as -1.

@ericsoderberghp

**Comment by elronalds** [comment]
@alansouzati I've committed another update to fix the issue if the legend is disabled.  Not sure I'm following along there regarding the `defaultXIndex`.  The reason I added the `hoverOnly` property was someone might always want the legend to appear so I've made this an optional setting for now.

@ericsoderberghp

**Comment by bryanjacquot** [comment]
@elronalds: we have some new chart capabilities coming soon where this capability won't be required.  We will keep this PR open until we've verified this issue is no longer present.

**Comment by bryanjacquot** [comment]
The new chart component addresses this issue.  http://grommet.github.io/docs/chart

**Pull request closed without merging**
