### PR TITLE
Add FileDropzone component to grommet-core

### PR DESCRIPTION
**Pull request by RyanCCollins**
Adds the file dropzone component to grommet-core.  This component was developed for use in the grommet-cms and it's been proposed that it could be of some use in grommet-core.

I would love to get some feedback on how we could possibly improve this.

#### What does this PR do?
See above

#### Where should the reviewer start?
src/js/components/FileDropzone.js / see diff

#### What testing has been done on this PR?
Manual integration testing.  Automated snapshot testing.

#### How should this be manually tested?
View this pr for the documentation site and play around with the component.

#### Any background context you want to provide?
This was built for the grommet-cms site and is in use in multiple deployments of it.

#### What are the relevant issues?
https://github.com/grommet/grommet/issues/1191

#### Screenshots (if appropriate)
image

#### Do the grommet docs need to be updated?
Yes, and it already has been. See here https://github.com/grommet/grommet-docs/pull/263

#### Should this PR be mentioned in the release notes?
Yes 😄 

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible.

### CODE REVIEW

**Comment by RyanCCollins** [comment]
I just had a discussion with @alansouzati.  It sounds like we are going to work to get this into Grommet 2.0.  We've had a discussion about changing the API a bit, so when we start work on 2.0 I will re-introduce this.

**Comment by RyanCCollins** [comment]
Someday 😄

**Comment by RyanCCollins** [comment]
I've merged with master and updated to pass the CI suite.

**Comment by RyanCCollins** [comment]
@alansouzati if you get a chance, let me know what your thoughts are on this.  I completely understand if we don't want to add it to core.  Just want to get the convo going to see if there is a place for it somewhere.

**Comment by panigrah** [comment]
@RyanCCollins - the file gets uploaded twice if fullTargetDrop is set to true and I drop into the dropzone. Do we need to stop propagating the event if the onDrop?

**Comment by panigrah** [comment]
@RyanCCollins another issue in `_onClearFilePreview(i)` its missing the 

        const { onDOMChange } = this.props;

and the `onDomChange.call()` needs to pass `i` instead of `e`

**Comment by RyanCCollins** [comment]
@panigrah thank you for helping to test this!  Are you interested in contributing?  Feel free to push to this branch if so.

**Comment by panigrah** [comment]
@RyanCCollins i can try - how do I push to the branch?

**Pull request closed without merging**
