### PR TITLE
Align option added to Drop's stretch prop

### LINKED ISSUE #2428: v2 Select: optionally tell Drop within select to respect the width of the main Select target
Today if the content inside the Drop is bigger than the Target, the drop will expand. it would be nice to have a way to tell the Drop to wrap and fix position so that the Select options are always aligned to the end of the target.

### PR DESCRIPTION
**Pull request by IanKBovard**
#### What does this PR do?
Adds a constrain prop to select component that restricts the width of the drop to the width of the select.

#### Where should the reviewer start?
DropContainer.js
DropButton.js
Select.js

#### What testing has been done on this PR?
Manual testing. Storybook

#### How should this be manually tested?
Storybook

#### What are the relevant issues?
closes #2428 

#### Screenshots (if appropriate)
Default behavior - w/o constrain :
Screen Shot 2020-09-02 at 5 39 07 PM

with constrain :
Screen Shot 2020-09-02 at 5 39 13 PM

#### Do the grommet docs need to be updated?
Yes

#### Should this PR be mentioned in the release notes?
No

#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Comment by IanKBovard** [comment]
I will update the docs, add a story, and a test once this solution is approved. Just not sure if we want to take this approach.

**Comment by ShimiSun** [comment]
Does the terminology `fit` would work better? It will be more grommet consistent.

**Comment by ericsoderberghp** [comment]
Two thoughts:
- I think we should connect this up to the `stretch` prop in Drop somehow, maybe `stretch="align"`? Open to exploring other values.
- I think we should do this on Drop and then rely on `dropProps` of Select, and Menu, rather than making it a formal property of Select.

**Comment by IanKBovard** [comment]
> * stretch

Ill make those changes

**Comment by IanKBovard** [comment]
changes made.
stretch prop now has align.
docs updated.

**Review by ericsoderberghp — DISMISSED** [review]

**Comment by ericsoderberghp** [comment]
Can we also add `stretch="align"` to the unit tests?

**Comment by ericsoderberghp** [comment]
I had been thinking we'd update Drop-test.js, where we have a test for the `stretch` prop.

**Review by ericsoderberghp — APPROVED** [review]

**Review by ShimiSun — APPROVED** [review]

**Comment by ShimiSun** [comment]
Thank you @IanKBovard !

**Pull request merged**
