### PR TITLE
remove leftover index-icons require #485

### PR DESCRIPTION
**Pull request by primozs**
#485 
Application build fails with grommet stabile.

### CODE REVIEW

**Comment by alansouzati** [comment]
good catch @primozs. In fact index-icons is not a left-over. it should be there. I'm going to investigate why it is not present in grommet stable.

**Comment by primozs** [comment]
@alansouzati I see its fixed..
Cheers

**Comment by alansouzati** [comment]
almost fixed. i had to fix manually. im still investigating why the CI is ignoring this file.

**Comment by primozs** [comment]
This is in gitignore 
```
**index-icons**
```

**Comment by alansouzati** [comment]
stable branch does not have the git ignore.

basically index-icons should be present in stable branch, but ignored from master branch as it is an automatically generated file.

`gulp generate-index-icons` is the task responsible for creating this file.

**Comment by primozs** [comment]
@alansouzati Interesting, I thought that to build grommet all you need is to run `gulp dist`. but this does not run `generate-index-icons` for index-icons to be build `gulp dist-bower` needs to be run also.
Is this ok?

**Comment by alansouzati** [comment]
I fixed the ci issue, for local build `gulp dist` should be enough. In the ci system the process is a little different. Thanks for helping!

**Pull request closed without merging**
