### PR TITLE
Datatable interaction implementation

### PR DESCRIPTION
**Pull request by oorestisime**
#### What does this PR do?

- [x] Adds on row click to TableRow
- [x] Handle hovering when onRowClick is defined
- [x] Handles onRowClick in datatable
- [x] Handles selection in datatable 
- [ ] keyboard interaction is not there yet

#### Where should the reviewer start?

Code for handling selection makes a couple of assumptions

- (non breaking) user defines in list of columns an object describing the checkbox column. When not set and selectable is true we add our own "makeshift" checkbox column
- (probably breaking ) user sets primaryProperty (hence the warning when not set ). current state of things when not set is weird behaviour due to not knowing how to set proper keys for selection list

#### What testing has been done on this PR?

storybook. both of stories are good examples.

- [ ] i ll try and add unit-test  later

#### How should this be manually tested?

storybook

#### Any background context you want to provide?

#2708 

#### What are the relevant issues?
#2708
#### Do the grommet docs need to be updated?
haven't touched yet
- [ ] documentation
#### Should this PR be mentioned in the release notes?
yes
#### Is this change backwards compatible or is it a breaking change?
yes

### CODE REVIEW

**Comment by oorestisime** [comment]
tests are failing because i haven't yet updated snapshots

**Comment by ericsoderberghp** [comment]
A couple of initial comments:
- I think solely representing selection via a checkbox feels too opinionated to me. I would like to discuss this with @L0ZZI a bit to show some other design approaches that we might want to accommodate as well.
- I didn't see how the caller can populate any initial selection state or receive notification when the selection changes. Perhaps I am missing something.

**Comment by oorestisime** [comment]
> A couple of initial comments:
> 
>     * I think solely representing selection via a checkbox feels too opinionated to me. I would like to discuss this with @L0ZZI a bit to show some other design approaches that we might want to accommodate as well.
> 

do you mean adding theme capability for another icon? Or like row changes background or so?

>     * I didn't see how the caller can populate any initial selection state or receive notification when the selection changes. Perhaps I am missing something.

* nice idea about the initial selection state. i ll integrate this.
* about the notification i call here the onRowClick callback https://github.com/grommet/grommet/pull/2739/files#diff-1db494bb9da8b05f33e989ad88b1ea92R100 . were you expecting something different? I admit i am not callibg the callback when user clicks on select all, but i can definitely add this. I am just not sure it makes sense to send all the data back.

**Comment by ericsoderberghp** [comment]
> do you mean adding theme capability for another icon? Or like row changes background or so?

It could be a background change, a border change, or a different icon.

**Comment by ericsoderberghp** [comment]
> about the notification i call here the onRowClick callback, were you expecting something different? I admit i am not callibg the callback when user clicks on select all, but i can definitely add this. I am just not sure it makes sense to send all the data back.

I'm envisioning it being able to be used as an uncontrolled component, in other words, the caller supplies the initial selected items, as the user adds and removes items, the caller can keep track of what is selected. Just using `onRowClick` requires the caller to check whether the row was selected or not and update his state. One way to accomplish this could be to align with `Select` and have `value` and `onChange` properties.

**Comment by oorestisime** [comment]
> > do you mean adding theme capability for another icon? Or like row changes background or so?
> 
> It could be a background change, a border change, or a different icon.

i was thinking about this. The background and border will have to be handled by TableRow directly so would this makes sense to have it on another PR when we have input from @L0ZZI ? I mean it wouldn't be a breaking change or anything just setting a prop selected on tablerow and then handling this with the theme.

**Comment by ShimiSun** [comment]
@oorestisime I'm trying to do some cleanups, is this still on track?

**Comment by oorestisime** [comment]
not exactly on track. maybe eric will continue this since he was going to work on datatable.

**Comment by ShimiSun** [comment]
I'm reopening this one because it allows selection and a little more interactions than the PR that just got merged. we will link the other interaction improvements to this PR.

**Comment by oorestisime** [comment]
But its totally outdated. better link to the issue #2708 no?

**Comment by ShimiSun** [comment]
good catch, we can link it to both. Even if it is an outdated PR, we said we'll keep it open as a reference if needed. we want to make sure we are covering all interactions.

**Comment by ShimiSun** [comment]
I think DataTable is in a different place today since this PR, and hence I'll be closing it, thank you!

**Pull request closed without merging**
