### PR TITLE
Add onKeyPress event to Search Component

### PR DESCRIPTION
**Pull request by epilande**
I would like to capture Keyboard events on the search input. 

For example, the `Enter` key:
```javascript
  _onKeyPress(event) {
    if (event.key === 'Enter') {
      // do stuff
    }
  }
```

### CODE REVIEW

**Comment by alansouzati** [comment]
Thanks for your contribution @epilande. 

I'm wondering how we would handle all other events like keyup, mouse events, and so on...

Initially, I would prefer handling these events outside the search component. But I'm happy to hear from you if you don't agree.

I've created a [code pen](http://codepen.io/alansouzati/pen/zrBZGX?editors=001) to illustrate how I would implement outside the search component, let me know what you think.

**Comment by alansouzati** [comment]
Another related question, are you waiting to add the enter listener to submit a request? If yes, is the search component inside a form?

**Comment by epilande** [comment]
Hi @alansouzati, I implemented your CodePen example with my existing code & that works. Are there any documentations on KeyboardAccelerators?

**Comment by alansouzati** [comment]
Unfortunately not. That would be a great PR for the grommet docs site :)

**Pull request closed without merging**
