### PR TITLE
Fixed layer on mobile to take full width and height

### PR DESCRIPTION
**Pull request by alansouzati**
#### What does this PR do?
Changes layer on mobile to make sure it takes full width and height

#### Where should the reviewer start?
StyledLayer

#### What testing has been done on this PR?
manual

#### How should this be manually tested?
open full example on layer stories
#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
yes
#### Is this change backwards compatible or is it a breaking change?
backwards

### CODE REVIEW

**Comment by alansouzati** [comment]
This also fixes a problem where the layer in mobile does not scroll

**Comment by ericsoderberghp** [comment]
There doesn't appear to be an issue for this. I'd like to see how to reproduce the problem without the fix in order to evaluate it more. Of note, StyledLayer is already:
```
position: absolute;
width: 100%;
height: 100%;
min-height: 100vh;
```
and the StyledContainer is:
```
position: relative;
top: 0;
bottom: 0;
left: 0;
right: 0;
```
I would think this would have the container fill the entire layer. With `width: 100vh`, I would think there could be scenarios where the container wouldn't be as tall as it would be without that.

**Comment by alansouzati** [comment]
Just try the layer on mobile you will see this issue. Also try my Pr locally you will ser I added different colors so that you can see the layer will take full height on mobild

**Comment by ericsoderberghp** [comment]
I see the issue! I'm concerned about how the proposed fix will behave on actual mobile devices. Those devices, at least iOS, scroll more smoothly when the scrolling is at the body/page level and not within a div managed by CSS. My inclination is to explore using `min-height: 100vh` if at all possible in both Layer and LayerContainer.

**Comment by ericsoderberghp** [comment]
I still want to do some more tests on a real mobile device. But, this is definitely an improvement.

**Pull request merged**
