### PR TITLE
Anchor title support

### PR DESCRIPTION
**Pull request by arjunbm468**
#### What does this PR do?
Make the Anchor component to support HTML title attribute, which is used to display extra information about the element in the browser supported tool-tip.
#### Where should the reviewer start?
Only Anchor.js is changed.
#### What testing has been done on this PR?
It has been tested on grommet-docs project. I have always created pull request https://github.com/grommet/grommet-docs/pull/67 to demonstrate the example and updated documented as well.
#### How should this be manually tested?
Can be tested in grommet doc once that pull request is merged.
#### Any background context you want to provide?
HTML title attribute is very useful http://www.w3schools.com/tags/att_global_title.asp  and beneficial for few hyperlinks.
#### What are the relevant issues?
Anchor component  will not be able to display tooltip.
#### Screenshots (if appropriate)
Nope
#### Do the grommet docs need to be updated?
Yes. Already updated at https://github.com/grommet/grommet-docs/pull/67
#### Should this PR be mentioned in the release notes?
No.
#### Is this change backwards compatible or is it a breaking change?
Backward compatible.

### CODE REVIEW

**Comment by arjunbm468** [comment]
@alansouzati @ericsoderberghp 

Please review and merge to master if you really want to support title attribute in ANCHOR component.

If you agree with this, then grommet docs pull request should also be merged..
https://github.com/grommet/grommet-docs/pull/67

**Comment by alansouzati** [comment]
Thanks for your contribution.

For a text anchor, why we need a title? Grommet does not recommend using title for tooltip or help purposes.

The lack of support for title in Anchor as of today is intentional.

Can you illustrate a scenario where the title for a text anchor will be useful rather than for help/tooltip purposes?

**Comment by arjunbm468** [comment]
In my application, We have links present on the left navigation menu of a page.
Some links requires additional privileges to access them.

When the user hovers on those link, we present them with a tool-tip saying **Requires an active software updates support agreement.**

Attached images illustrates this...
 
navigation

**Comment by alansouzati** [comment]
This is not accessible. Imagine if your are blind, screen readers will read: "Requires an active hardware contract". He has no idea about "Diagnostic passwords".

Using title to provide help/tooltip is an anti-pattern for Grommet.

We will soon provide support for transferring props in Anchor, similar to the way we do it in Box. With that we will be able to do things like this, but we don't recommend it.

**Pull request closed without merging**
