### PR TITLE
HTML onchange

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
This PR potentially fixes a bug found with onchange in form  
#### Where should the reviewer start?
form.js
#### What testing has been done on this PR?
storybook and grommet project linked to grommet core
#### How should this be manually tested?
```
class App extends Component {
  render() {
    let value = {
      title_fr: "Title fr",
      title_en: "Title en"
    };
    return (
      <Grommet theme={grommet}>
        <Box pad="small">
          <Form
            onSubmit={({ value }) => this.save(value)}
            onChange={value => console.log(value)}
            value={value}
          >
            <FormField label="Title (FR)" name="title_fr" />
            <FormField label="Title (EN)" name="title_en" />
          </Form>
        </Box>
      </Grommet>
    );
  }
}
```
#### Any background context you want to provide?
Currently onChange was added into onReset and upDate functions. 
Since we were using ` <form {...rest} onReset={this.onReset} onSubmit={this.onSubmit}>`
it was using passing the HTML onchange. Since this was the case in the original issue you can see that the object was being console.log twice which the second object the correct event. 
There is no actual onChange function which may be something we discuss.
#### What are the relevant issues?
#3356 
#### Screenshots (if appropriate)
N/A
#### Do the grommet docs need to be updated?
No
#### Should this PR be mentioned in the release notes?
No
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Comment by ShimiSun** [comment]
Let's test this one with onChange on Form, I want us to make sure it works properly and not creates a backward compatibility issue for users who had been using onChange for Form.

**Comment by britt6612** [comment]
@ShimiSun sounds good I will test this also with that as well!

**Comment by britt6612** [comment]
@ShimiSun after some more digging into this problem turns out that
the warning about the `SyntheticEvent` object is because React reuses the `SyntheticEvent` by polling the synthetic events all together that is why in the `syntheticevent` it is returning null after an event is called back. 

Essentially, `SyntheticEvent` cannot be used asynchronously, because the event will no longer exist after the event callback has been invoked.

Im investaging another way in which we can leverage the event.persist() to maybe fix this issue as well as looking at other things.

**Comment by ShimiSun** [comment]
OK, sounds good, feel free to reopen the PR or file a new one when relevant.

**Pull request closed without merging**
