### PR TITLE
Changed TextArea to add fill.

### PR DESCRIPTION
**Pull request by ericsoderberghp**
#### What does this PR do?

Changed TextArea to add fill.
Updated TextInput doc to specify `onChange` instead of `onInput`. See: https://stackoverflow.com/questions/38256332/in-react-whats-the-difference-between-onchange-and-oninput#40003179
Fixed an issue with Calendar unit test not being immune to wall clock time changes.

#### Where should the reviewer start?

TextArea/doc.js

#### What testing has been done on this PR?

storybook

#### How should this be manually tested?

storybook

#### What are the relevant issues?

https://github.com/grommet/grommet/issues/2405
https://github.com/grommet/grommet/issues/2412

#### Do the grommet docs need to be updated?

yes

#### Should this PR be mentioned in the release notes?

yes

#### Is this change backwards compatible or is it a breaking change?

backwards compatible

### CODE REVIEW

**Comment by alansouzati** [comment]
I think we cannot move away from onInput. copy and paste does not trigger the onChange. We used to have onChange in the past and we moved to onInput because of that.

**Comment by ericsoderberghp** [comment]
> I think we cannot move away from onInput. copy and paste does not trigger the onChange. We used to have onChange in the past and we moved to onInput because of that.

Did you read the stackoverflow post though? The latest react complains if you have `value` without `onChange`.

**Comment by alansouzati** [comment]
maybe we need both then?

**Comment by alansouzati** [comment]
I just tested the copy and paste and work in the latest react!!

I believe it is safe to move back to onChange :)

Can we also change TextInput ? also, it would be great to update all stories to not use `onInput`

**Comment by ericsoderberghp** [comment]
> I just tested the copy and paste and work in the latest react!!
> 
> I believe it is safe to move back to onChange :)
> 
> Can we also change TextInput ? also, it would be great to update all stories to not use `onInput`

Good idea. I've removed all vestiges of `onInput`. Note the interesting change I had to make to how we `fireEvent.change()` to send actual event data. Without that, the event would not be delivered. I like how react-testing-library tries to make things as real as possible.

**Pull request merged**
