### PR TITLE
Layer closer position outside

### PR DESCRIPTION
**Pull request by epilande**
Allow closer to be positioned outside of layer. 

image

### CODE REVIEW

**Comment by alansouzati** [comment]
thanks for your contribution.

We've wanting to remove the close support from the layer. This is another evidence that it actually makes sense to do so. There are so many different ways to display the close icon inside a layer that makes it dangerous to start adding properties for the different positions such as "outside".

@ericsoderberghp would love your insight here.

**Comment by bryanjacquot** [comment]
Agreed with @epilande to wait for final designs before proceeding with this PR.

**Comment by karatechops** [comment]
I just wanted to chime in real quick and add my recent experience with the Layer closer. 
Recently I had a project which required a layer with a fixed closer position. This was necessary because the Layer had quite a bit content which required scrolling. Requiring the user to scroll to the bottom and then scroll back up to the top is probably not optimal UX.

**Comment by alansouzati** [comment]
currently the Layer has the "esc" listener that will close the layer. I would risk to say that pressing esc to close is a fairly known feature for layers.

I worry about putting the close outside the layer, specially for mobile when we convert the layer to have full width + height.

**Pull request closed without merging**
