### PR TITLE
fix two deadlinks in the readme.md

### PR DESCRIPTION
**Pull request by ellerbrock**

### CODE REVIEW

**Comment by alansouzati** [comment]
Thanks for your contribution.

**Comment by ellerbrock** [comment]
no worries, im glad when i can help.
i found another problem, this time in the gh-pages.
i try to fix it and send u a pr later on ...

**Comment by alansouzati** [comment]
looking forward to it 😄

**Comment by ellerbrock** [comment]
lol i wasted now more time trying to make a simple git pull from your master in my repro via github web interface in my fork. im too stupid :) i tried then changing the head to your repro but still told me 2 branches back. just for interest, is this via web interface not possible? so far i just killed my repro and reforked it which seems to be faster then changing the git remote bla bla ... the funny part is that i just saw its the wrong repro anyway, i thought u have the gh-pages as a branch but it have its own repo :) so fix goes also in this repo in case i can find the problem ...

**Comment by alansouzati** [comment]
This repo https://github.com/grommet/grommet.github.io is read only. Usually our bot updates it.

Can you describe what the issue is? I'm almost sure whatever the issue is the fix will be in the grommet-docs project: https://github.com/grommet/grommet-docs.

Sorry for not proving better documentation around our documentation structure.

**Comment by ellerbrock** [comment]
Its a quick fix but a real bad user experience - its the first contact with the code in the hello world example: http://grommet.github.io/docs/hello-world
when you open the developer tools you can quick see where the problem is coming from.

404) = > http://www.grommet.io/assets/latest/grommet.min.js
fix) =>https://grommet.github.io/assets/latest/grommet.min.js

404) => http://www.grommet.io/assets/latest/css/grommet.min.css 
fix) =>https://grommet.github.io/assets/latest/css/grommet.min.css

i just was thinking for myself few days before how to solve this 404 problem best in github.
i have more and more markdown files lots of links in awesome like lists which i would like to scan automatically now and then for deadlinks. do you know if there is already a solution for that? i was thinking via travis or greenkeeper or something like that to run the tests ...

**Comment by alansouzati** [comment]
good catch, in fact my manager @bryanjacquot found it before you, which is super bad hahha

We are fixing it already. I'm afraid the fix is even already pushed. In case you are curious the fix would be here: https://github.com/grommet/grommet-docs/blob/master/server/server.js

**Comment by ellerbrock** [comment]
ah ok, in fact i just was searching where this is coming from.

in case you patch this now anyway, why not change the links from http to https?
github runs https default anyway, bit more secure and don't have to deal with mixed contend warnings or something ...

**Comment by alansouzati** [comment]
you bet! @ericsoderberghp look at this nice tip from our friend @ellerbrock

**Comment by ellerbrock** [comment]
its totally off-topic but since you work with grommet i'm just asking. since a few days im switching my dev workflow from angular 1.5 with material design to react, redux and was looking for a css framework for that job. i had not the time yet to look closer to grommet but i saw you guys also running react under the hood. did u build it component based which would be awesome. and second question, i saw its still 0.4x or something and some issues and pr's which is good so active community, but my question would you run it for production or is it to early? i like the clean and simple design. another lib for react looking good was this one: http://react-toolbox.com (react version of material design).

**Comment by alansouzati** [comment]
Good questions. 

We are definitely production ready. Although we are still in `0.X` stage, we have apps in production today. Check this one out: http://hc380.grommet.io (any username and password is accepted).

We have folks outside Hewlett Packard Enterprise using it in production today. @eabay @linde12 that I can remember.

Regarding your component-based questions, yes, we are modular, so you only pay for what you use.

React toolbox is really cool. I can't speak much about them because I don't have a lot of experience.

Grommet has a lot of cool components focused for enterprise apps like: 

http://grommet.github.io/docs/chart
http://grommet.github.io/docs/meter
http://grommet.github.io/docs/topology
http://grommet.github.io/docs/world-map

and more...

Accessibility is also built-in to grommet components. Even for the chart and meters that are SVG components. Accessibility is a core requirement for most enterprises.

Your question makes me think we should write something around "Why Grommet?"  😄

**Comment by alansouzati** [comment]
Please join our slack channel if you have any more questions around Grommet: httphttp://slackin.grommet.io

**Comment by ellerbrock** [comment]
damn hc380 looks sexy! and very nice to hear that it is component based and ready to roll.
i will definitly have soon a closer look! im not sure if you guys already have something like that but i also just looked before for the react-toolbox framework and they provide a minimal react starter pack for beginners. since im the perfect fit to speak about that because i just started to look and play with react few days before. i think a starter kit would be for u a easy fast task and could increase popularity for people new to react to quick get started. just an idear ...

**Comment by ellerbrock** [comment]
that was the repo i was talking about:
https://github.com/react-toolbox/react-toolbox-example

**Comment by alansouzati** [comment]
We have just released the grommet-cli with few templates: https://github.com/grommet/grommet-cli

Also we have the grommet-toolbox that offers series of useful tasks for developers: https://github.com/grommet/grommet-toolbox

**Comment by ellerbrock** [comment]
perfect, really good work you guys doing there. i found about the cli tool when i searched you on twitter and made a reetweet (https://twitter.com/frapsoft). vorpal looks very interesting too :)
thats almost a problem with the full stack js world. u learn one thing and meanwhile learning how to use it find so many awesome other cool things also need to learn later on :) anyway, was very nice to talk with you guys and all the best with your project for the future. i will later on definitly have a closer look ... cheers maik

**Pull request merged**
