### PR TITLE
Styles for align="stretch" prop for Box

### PR DESCRIPTION
**Pull request by codeswan**
Add scss style so the existing `align="stretch"` and `alignContent="stretch"` options on Box work.

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
I thought "stretch" was the default for both properties, as in not specifying the property meant you got stretch. Is that not true or not working?

**Comment by codeswan** [comment]
@ericsoderberghp You are correct. Closing this PR.

**Comment by jameswyse** [comment]
I was having similar problems getting stretch working on `Box`. I thought the problem was those missing classes as well at first, which is how I found this issue.

The default for `align-items` / `align-content` is `"stretch"` but flex items don't grow by default (they will shrink in most cases though). Simply adding `flex-grow: 1` to the children fixed it.

**Comment by jameswyse** [comment]
Oh I just noticed the following in [_objects.box.scss](https://github.com/grommet/grommet/blob/master/src/scss/grommet-core/_objects.box.scss#L11-L14):

```css
// temporary flex grow capability
.box > .flex {
    flex-grow: 1;
}
```

So it seems the tempoary solution is to apply the `flex` class to children you want to grow :)

**Pull request closed without merging**
