### PR TITLE
Test coverage for various component

### PR DESCRIPTION
**Pull request by arjunbm468**
Added the test cases for components: CheckBox, RadioButton, SocialShare, TBD, Tag and Tags.
#### What does this PR do?
Enhances the test coverage
#### Where should the reviewer start?
newly added test/*-test.js files
#### What testing has been done on this PR?
gulp test
#### How should this be manually tested?
gulp test
#### Any background context you want to provide?
Contributing and learning
#### What are the relevant issues?
N/A
#### Screenshots (if appropriate)
N/A
#### Do the grommet docs need to be updated?
No
#### Should this PR be mentioned in the release notes?
No
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Comment by arjunbm468** [comment]
@alansouzati @ericsoderberghp 

Please review this and merge to master...
Not sure why the build has failed, probably an issue in build environment...

**Comment by alansouzati** [comment]
thanks

**Comment by alansouzati** [comment]
@arjunbm468 we are refactoring our test framework to use Jest. See this branch here: https://github.com/grommet/grommet/tree/JEST_EXPLORATION.

I will make sure to move all these tests to the new one. The merge should happen soon, I will keep you posted about it.

**Comment by arjunbm468** [comment]
Thanks a lot... @alansouzati

**Comment by alansouzati** [comment]
@arjunbm468 we finished the test migration, checkout this blog post to understand what is going one: https://blog.grommet.io/post/2016/09/01/how-we-landed-on-jest-snapshot-testing-for-javascript.

Whenever you are writing tests now, could you please create one github issue for each test you are writing? This way it will avoid us to work on the same test.

**Pull request merged**
