### PR TITLE
Suppress DOMExceptions on hiding Layer (#6888)

### PR DESCRIPTION
**Pull request by stephanpelikan**
#### What does this PR do?

Suppress DOMExceptions on hiding `Layer` (see #6888).

#### Where should the reviewer start?

Good question. There are only minor code changes which and this should not effect functionality. But maybe suppressing the DOMException unhides other problems. In my manual testing I didn't see this, but maybe I overlooked something.

#### What testing has been done on this PR?

Rerun automated tests. As well as manual tests.

#### How should this be manually tested?

Since this is hard to reproduce, just hiding a `Layer`.

#### What are the relevant issues?

#6888

#### Screenshots (if appropriate)

This screenshot shows that the error is gone using this PR:

grommet3

One the left side you can see the header and the menu which proofs that rendering is fine on using this PR.

#### Do the grommet docs need to be updated?

No

#### Should this PR be mentioned in the release notes?

Yes

#### Is this change backwards compatible or is it a breaking change?

It is backwards compatible

### CODE REVIEW

**Comment by taysea** [comment]
Thanks for filing this PR. It would be ideal if we could fix the Layer behavior in a way that no console errors or warnings would occur.

I took a look at the original issue you filed, and based on that it seems like before we try to `removeChild` we should check if `clone` is still a child of the `containerTarget`. (see code below).

current layer code:
```
 if (clone) {
              containerTarget.removeChild(clone);
              layerContainer.remove();
            }
```

I think we could leverage something like `containerTarget.contains(clone)`. Do you mind trying that out and updating your PR if that works?

**Comment by stephanpelikan** [comment]
I updated as you suggested and tested the code and it works perfectly fine. 😄

**Review by jcfilben — APPROVED** [review]
Looks good!

**Review by taysea — APPROVED** [review]
Great, thanks!

**Comment by stephanpelikan** [comment]
Thank you 👍 😄

**Pull request merged**
