### PR TITLE
Support multipart form data in utils/Rest

### PR DESCRIPTION
**Pull request by simula67**

### CODE REVIEW

**Comment by alansouzati** [comment]
Thanks for your contribution, but have you consider doing the following?

```javascript
  let postRest = Rest.post(`/api/post/`)
      .field('title', post.title)
      .field('author', post.author)
      .field('tags', post.tags || '')
      .field('content', post.content);

      if (post.images) {
        post.images.forEach((image) => {
          if (image.cover) {
            postRest.field('cover', image.name);
          }
          postRest.attach(image.name, image.file, image.name);
        });
      }

      postRest.end((err, res) => {
        if (err) {
          reject(err);
        } else {
          resolve(res.body);
        }
      });
```

See this for an example of sending multi-part data to a post request:

https://github.com/grommet/grommet-blog/blob/master/src/js/store.js#L70

**Comment by simula67** [comment]
@alansouzati  Shouldn't this be supported directly by grommet though ?

**Comment by alansouzati** [comment]
I like the idea of supporting this directly in grommet. but I have concerns with being opinionated about the data structure that must be sent. In your PR, data now needs to be in a specific format correct?

```javascript
   Object.keys(data.fields).map(function(key) {
      op.field(key, data.fields[key]);
   });
   Object.keys(data.formfiles).map(function(formfile) {
     op.attach(formfile, data.fields[formfile]);
   });
```

you are expecting `data.fields` and `data.formfiles` to be present.

I would not expect that restriction for such a high level utils component.

**Comment by simula67** [comment]
Thanks for the feedback, I have modified accordingly. I also added a workaround for an issue we were noticing with superagent.

**Comment by alansouzati** [comment]
So, in this new version you don't handle attaching files do you?

I believe this second version is better than the first one, but still assumes that every key inside your data will be used as a form data field, which is not always true. Let's take the following example:

```javascript
let postRest = Rest.post(`/api/post/`)
      .field('title', post.title)
      .field('author', post.author)
      .field('tags', post.tags || '')
      .field('content', post.content);

      if (post.images) {
        post.images.forEach((image) => {
          if (image.cover) {
            postRest.field('cover', image.name);
          }
          postRest.attach(image.name, image.file, image.name);
        });
      }

      postRest.end((err, res) => {
        if (err) {
          reject(err);
        } else {
          resolve(res.body);
        }
      });
```

The post object is like this:

```json
{
  "title": "simula67 is a great guy",
  "author": "Joji Antony",
  "images": [
    {
      "cover": true,
      "name": "joji_avatar",
      "file": ...
    }
  ]
}
```

I believe images key will fail in your existing pull request.

**Comment by simula67** [comment]
Attaching files *are* handled. If you use [FormData.append()](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append), there is no need to differentiate between fields and files. For append, the third argument ( filename ) is optional and I felt it best to leave it to the default behavior. I can add the third field based on a simple `instanceof` check, if you think that is better. MDN says it should be handled by the browser though.

**Comment by bryanjacquot** [comment]
The new Grommet Rest utility uses Fetch instead of Superagent.   This is no longer is applicable.

**Pull request closed without merging**
