### PR TITLE
Add missing 'pad' definition for Drop (#6467)

### PR DESCRIPTION
**Pull request by stephanpelikan**
#### What does this PR do?
Add missing pad property in DropProps interface definition which is already used by the underlying implementation.

#### Where should the reviewer start?
Check changed DropProps definition.

#### What testing has been done on this PR?
Unfortunately, not. I wanted to use it in my project to test it but when I try to build the bundle I get this error:
```
npm ERR! While resolving: grommet@2.27.99
npm ERR! Found: styled-components@5.3.6
npm ERR! node_modules/styled-components
npm ERR!   dev styled-components@"^5.3.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer styled-components@"^4.0.0" from grommet-theme-aruba@0.1.2
npm ERR! node_modules/grommet-theme-aruba
npm ERR!   dev grommet-theme-aruba@"^0.1.2" from the root project
```

#### How should this be manually tested?
I would, if I could ;-)

#### Do Jest tests follow these best practices?
- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### Any background context you want to provide?
none

#### What are the relevant issues?
https://github.com/grommet/grommet/issues/6467

#### Do the grommet docs need to be updated?
Yes

#### Should this PR be mentioned in the release notes?
As you which ;-)

#### Is this change backwards compatible or is it a breaking change?
It is backwards compatible

### CODE REVIEW

**Review by britt6612 — APPROVED** [review]

**Comment by jcfilben** [comment]
Drop can accept `pad` because on line 326 of DropContainer we pass `as={Box}` to StyledBox. So really Drop should be able to accept any props passed to Box but we don't document this. I'm wondering if we accept this change if we need to add other Box props, and add these to the index.d.ts, propTypes.js, and documentation.

**Comment by britt6612** [comment]
> Drop can accept `pad` because on line 326 of DropContainer we pass `as={Box}` to StyledBox. So really Drop should be able to accept any props passed to Box but we don't document this. I'm wondering if we accept this change if we need to add other Box props, and add these to the index.d.ts, propTypes.js, and documentation.

yeah as well as add this in the docs.. Just didn't want to block @stephanpelikan with the `pad` definition.

**Comment by britt6612** [comment]
> Member

@stephanpelikan would you mind adding all box props for the TS definitions

**Comment by britt6612** [comment]
Im showing an error on my side wonder if we need to omit `onClick` 

Screen Shot 2022-11-13 at 8 11 30 PM

**Comment by stephanpelikan** [comment]
I could see the error by copying the index.d.ts into the node_modules folder of the project in which I'm using Grommet. My last change fixed that problem. I don't see any errors now, only a warning that <HTMLDocument> is deprecated but that warning existed already before my change.

**Review by jcfilben — APPROVED** [review]
Looks good!

**Comment by britt6612** [comment]
> I could see the error by copying the index.d.ts into the node_modules folder of the project in which I'm using Grommet. My last change fixed that problem. I don't see any errors now, only a warning that <HTMLDocument> is deprecated but that warning existed already before my change.

yes thank you for fixing looks good

**Review by ericsoderberghp — APPROVED** [review]

**Pull request merged**
