### PR TITLE
[Datatable] Add sortable property on columns

### PR DESCRIPTION
**Pull request by oorestisime**
Closes: #2634
Signed-off-by: Orestis Ioannou <oorestisime@gmail.com>

#### What does this PR do?
* Enable user to turn off sortable property on selective columns
#### What testing has been done on this PR?
storybook.
#### What are the relevant issues?
#2634
#### Do the grommet docs need to be updated?
done
#### Should this PR be mentioned in the release notes?
yes
#### Is this change backwards compatible or is it a breaking change?
compatible

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
I like the general direction of this. I think there are a few things that need ironing out still:
- We need to adjust the mouse pointer when over a row since it is a control surface.
- What happens if a cell contains an interactive element, like a link?
- I don't think we should expect that checkboxes would be the only way to represent whether a row is selected. I think we should also explore supporting a both a hover indicator and selection indicator for the whole row.

In the new stories, we are missing the bottom border for the header checkbox cell.

It might be better to split this into two pull requests, one to add `sortable`, which seems straightforward, and another for the click interaction.

**Comment by oorestisime** [comment]
>     * What happens if a cell contains an interactive element, like a link?

Right so i had the problem when both CheckBox onChange event was fired and onRowClick and i thought that there shouldn't be two of those at the same time. I haven't figured out how to fix this actually, open to suggestions.

>     * I don't think we should expect that checkboxes would be the only way to represent whether a row is selected. I think we should also explore supporting a both a hover indicator and selection indicator for the whole row.

That means integrating the selection logic directly into datatables ? Because the checkboxes were an example on what to do with the onRowClick event.

> It might be better to split this into two pull requests, one to add `sortable`, which seems straightforward, and another for the click interaction.

agreed. I will force-push this one to have only the sortable property and open a new one with the rest.

thanks for the quick review

**Comment by oorestisime** [comment]
so i splitted this PR. i am still not sure why travis is not running its checks on this PR.

**Comment by ericsoderberghp** [comment]
Thanks for your contribution.

**Pull request merged**
