### PR TITLE
Fix screenreaders not reading contents of clickable Cards

### PR DESCRIPTION
**Pull request by davidcalhoun**
#### What does this PR do?
Fixes an issue with screenreaders not being able to read inside of linked `Card` elements (where the `Card` has a `link` prop and/or an `onClick` prop).

Basically what is happening is that a `Card` will have `role="link"` and `aria-label="Box"`, and the screenreader will simply read out "link box".  The `aria-label` appears to override everything contained in the contents of the `Card`, without giving any indication to the user that there's more.

By removing the `aria-label` text, this allows the screenreader to read deeper.

This was originally observed with Windows 10 / NVDA / Firefox 49.  Can also be observed with:
* Windows 10 / NVDA / Chrome 54
* OSX / VoiceOver / Chrome 54
* OSX / VoiceOver / Safari 9.1.3

#### What testing has been done on this PR?
Tested the fix in the following:
* Windows 10 / NVDA / Firefox 49
* Windows 10 / NVDA / Chrome 54
* OSX / VoiceOver / Chrome 54
* OSX / VoiceOver / Safari 9.1.3

#### How should this be manually tested?
You can test with this Codepen: http://codepen.io/franksvalli/pen/mAgjmG?editors=0010

Use the Developer Tools to change this:
`aria-label="Box"`
to this:
`aria-label=""`

#### What are the relevant issues?
grommet/hpe-digitaltoolkit#160

#### Screenshots (if appropriate)
Videos below were recorded in Windows 10 / NVDA / Firefox 49

Before (click to play video):
[before](https://www.youtube.com/watch?v=sXPAMdB1wgQ "before")

After (click to play video):
[after](https://www.youtube.com/watch?v=A-e-84CjJdg "after")

#### Do the grommet docs need to be updated?
No

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

**Comment by alansouzati** [comment]
Interesting find. My only concern is with the screen reader reading too much content. This could be annoying to the user. 

The strategy I did in few other components was: have the role="group" set on the box and add a message to it: "(Press enter to select)". Does it make sense?

Maybe we can even remove the role="link" and add only aria-label.

Check out how I did in SunBurst:

https://github.com/grommet/grommet/blob/552fba4484da2234765d5c59e3a5c43a21247fe0/src/js/components/SunBurst.js#L226

**Comment by davidcalhoun** [comment]
Cool, yeah I think `role="group"` would be better and makes more logical sense for cards.

I'm not sure about that `aria-label` text working for all screenreader users though.  When using VoiceOver on OSX with Chrome, VoiceOver says the following: "press enter to select, group" and then it gives different instructions on how to enter the group, by pressing `ctrl`+`opt`+`shift`+`down key`.  When I press enter, nothing seems to happen.

**Comment by davidcalhoun** [comment]
@alansouzati Thanks for the feedback!  Please have another look.  For all Cards, I've added `role="group"` and `aria-label="Card"` (see my commend about `aria-label` above).

**Comment by davidcalhoun** [comment]
Updated based on feedback from @alansouzati:

```
we need to make that configurable
a11yTitle
default could be Card definitely
but we need to allow a11yTitle to be passed
and can we make role=”group"
the default for box?
then we dont need to pass role=”group” for Card
```

Not entirely sure why `aria-label="Card"` isn't showing up in the test snapshot, but it's definitely working for `hpe-digitaltoolkit`

**Comment by alansouzati** [comment]
thanks!

**Pull request merged**
