### PR TITLE
Changed Markdown to fix an issue with property placement

### PR DESCRIPTION
**Pull request by ericsoderberghp**
#### What does this PR do?

Fixes an issue where Markdown couldn't support `onClick`. This was due to `...rest` being placed on the Markdown component instead of its wrapping div. Since the Markdown wrapper is a Fragment, it was ignoring most of `...rest`. 

#### Where should the reviewer start?

Markdown.js

#### What testing has been done on this PR?

Integrated with grommet-designer

#### Do the grommet docs need to be updated?

no

#### Should this PR be mentioned in the release notes?

yes

#### Is this change backwards compatible or is it a breaking change?

backwards compatible

### CODE REVIEW

**Review by amandadupell — COMMENTED** [review]
looks good to me! my only thought is if there needs to be a new example of this behavior for Markdown in Storybook to show how we support the onClick now, just a thought!

**Comment by ericsoderberghp** [comment]
> looks good to me! my only thought is if there needs to be a new example of this behavior for Markdown in Storybook to show how we support the onClick now, just a thought!

I thought about that. But, this is a pretty obscure usage. It doesn't really make sense for most contexts to have the Markdown component be interactive, just something unique to grommet-designer.

**Review by jcfilben — APPROVED** [review]
Looks good to me!

**Review by amandadupell — APPROVED** [review]

**Review by MikeKingdom — APPROVED** [review]
LGTM!

**Pull request merged**
