### PR TITLE
Fix sideEffect path to point where user is going to import file

### PR DESCRIPTION
**Pull request by oorestisime**
Fix: #2669

So i got digging and reading documentation and talking with people :D and it seems that sideEffects should point to the file user is going to import.

I only tested this in the example provided in the issue above. i went into `node_modules/grommet/` and modified my self.

what got me into this fix was that i could import ThemeContext from the direct path

`import {ThemeContext} from "grommet/contexts"`

### CODE REVIEW

**Comment by ShimiSun** [comment]
@oorestisime this is great. can you share the documentation you were relying on to determine this fix?

**Comment by oorestisime** [comment]
mostly this https://github.com/webpack/webpack/tree/master/examples/side-effects

**Comment by ShimiSun** [comment]
I noticed this fix is causing a regression for storybook Accordion-> Rich and Drop->All not stretch. the two stories are broken due to using `ThemeContext` of undefined.
The side-effect should include both options.
screen shot 2019-03-07 at 10 00 44 pm

**Comment by oorestisime** [comment]
Ok added the previous side effect as well. makes sense as well since storybook is built from our source structure.

**Pull request merged**
