### PR TITLE
Add tip toggle group

### LINKED ISSUE #7254: ToggleGroup when icon only use Tip
### Is this something you or your team is interested in contributing a pull request towards?
I will do a PR and help Grommet team :)

### Expected Behavior
I would expect a way for a user to opt in having a tooltip when icon only is used in ToggleGroup

I cant do the above behavior
### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
This PR adds the option to add `tip` in `options` prop for ToggleGroup
#### Where should the reviewer start?
togglegroup.js
#### What testing has been done on this PR?
storybook &  wrote a test
#### How should this be manually tested?
storybook 
#### Do Jest tests follow these best practices?
yes
- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
closes #7254 
#### Do the grommet docs need to be updated?
yes
#### Should this PR be mentioned in the release notes?
yes
#### Is this change backwards compatible or is it a breaking change?
 backwards compatible

### CODE REVIEW

**Review by jcfilben — COMMENTED** [review]
Can we add `options.tip` to the PropTypes for ToggleGroup?

**Comment by britt6612** [comment]
> Can we add `options.tip` to the PropTypes for ToggleGroup?

added

**Review by jcfilben — APPROVED** [review]
Looks good!

**Review by MikeKingdom — APPROVED** [review]
lgtm

**Pull request merged**
