### PR TITLE
Changed Tabs base themeing

### PR DESCRIPTION
**Pull request by ericsoderberghp**
#### What does this PR do?

Changed Tabs base themeing

#### Where should the reviewer start?

base.js

#### What testing has been done on this PR?

storybook

#### How should this be manually tested?

storybook

#### What are the relevant issues?

https://github.com/grommet/grommet/issues/2403

#### Do the grommet docs need to be updated?

no

#### Should this PR be mentioned in the release notes?

yes

#### Is this change backwards compatible or is it a breaking change?

backwards compatible

### CODE REVIEW

**Comment by alansouzati** [comment]
this is a breaking change right since we are removing `weight` from the theme

**Comment by ericsoderberghp** [comment]
> this is a breaking change right since we are removing `weight` from the theme

We are still transferring any props to the internal Text, we are just transferring all of them.

**Comment by alansouzati** [comment]
I hear you, but we removed a property from the theme object, and if you were using it before, this would break.

**Comment by ericsoderberghp** [comment]
Ah, you mean since we are changing the default weight for tabs in `base.js`?  That seems comparable to some of the other styling changes we've made in base before, that we didn't declare to be "breaking". But, I'm OK flagging it that way.

**Comment by alansouzati** [comment]
yeah just to be explicit

**Pull request merged**
