### PR TITLE
Align DataFilters layer to Design System best practices

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?

Remove `size` from Heading, use `Close` instead of `FormClose`, align spacing of submit buttons to Design System best practices.

Since we haven't moved these out of beta yet, let's align the default state with Design System best practices.

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

### CODE REVIEW

**Comment by britt6612** [comment]
Im lost whats in beta? Is it the `size` from Heading?

**Review by jcfilben — COMMENTED** [review]
I good with these changes, looks like some additional snapshots need updated

**Comment by jcfilben** [comment]
> Im lost whats in beta? Is it the size from Heading?

I think what Taylor is saying is that since the Data an friends components in Grommet are in 'beta' mode it is okay for us to make these adjustments and not worry about backwards compatibility concerns

**Comment by britt6612** [comment]
> > Im lost whats in beta? Is it the size from Heading?
> 
> I think what Taylor is saying is that since the Data an friends components in Grommet are in 'beta' mode it is okay for us to make these adjustments and not worry about backwards compatibility concerns

right okay thanks

**Review by jcfilben — APPROVED** [review]
Looks good!

**Review by MikeKingdom — APPROVED** [review]
LGTM

**Comment by jcfilben** [comment]
Looks like there is a jest test snapshot that needs updated

**Pull request merged**
