### PR TITLE
Changed Calendar to honor reference when set

### PR DESCRIPTION
**Pull request by ericsoderberghp**
#### What does this PR do?

Changed Calendar to honor reference when set

#### Where should the reviewer start?

Calendar.js

#### What testing has been done on this PR?

Tried assorted stories.

#### How should this be manually tested?

Try various Calendar and DateInput stories. I'm sure I haven't covered everything from a testing perspective.

#### Do Jest tests follow these best practices?

no test changes

#### What are the relevant issues?

#6609 

#### Do the grommet docs need to be updated?

no

#### Should this PR be mentioned in the release notes?

yes

#### Is this change backwards compatible or is it a breaking change?

backwards compatible

### CODE REVIEW

**Review by jcfilben — COMMENTED** [review]
https://user-images.githubusercontent.com/54560994/228643830-0e5b140f-a58f-4c55-a8d4-978a322b107d.mp4

Noticing some strange behavior where the first time I try to select a range it doesn't work and then the second time it does.

**Comment by ericsoderberghp** [comment]
> Noticing some strange behavior where the first time I try to select a range it doesn't work and then the second time it does.

Should be working now, tweaked the story.

**Comment by jcfilben** [comment]
Now the first time I select a range it is working but the second time it doesn't work

https://user-images.githubusercontent.com/54560994/228899337-536b79b0-d2ca-492b-b833-dae8b947aa25.mp4

**Review by jcfilben — APPROVED** [review]
Looks good!

**Review by taysea — APPROVED** [review]
Good fix, thanks!

**Pull request merged**
