### PR TITLE
Fixed storybook complaning about missing path.

### PR DESCRIPTION
**Pull request by alansouzati**
#### What does this PR do?
fix an unexpected issue with storybook after changing the require statement in box

#### What testing has been done on this PR?
manual
#### How should this be manually tested?
run storybook
#### What are the relevant issues?
no issue
#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
no
#### Is this change backwards compatible or is it a breaking change?
backwards

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
What was the issue? On the surface, the two seem to be identical.

**Comment by tbranyen** [comment]
webpack is better at detecting template strings since this is generally used for dynamically importing pages, I had originally used a variable which webpack doesn't try to resolve.

**Comment by ericsoderberghp** [comment]
To see if I understand, does that mean that if we had: `doc = path => require(\`${path}\`).doc;` it would have worked?

**Comment by tbranyen** [comment]
Yeah that's my understanding, their AST crawling must expect a StringLiteral or TemplateLiteral

**Comment by ericsoderberghp** [comment]
I'm wondering then if `doc = path => require(`${path}`).doc;` would be clearer then, because the path would be only known to the component calling `doc()`. It feels a little hidden inside the utility function.

**Comment by alansouzati** [comment]
agreed. let me send a pr for this. sorry i've merged it too fast.

**Pull request merged**
