### PR TITLE
fix(formfield): missing select props

### PR DESCRIPTION
**Pull request by roger-king**
#### What does this PR do?

Potentially fix types for formfield 

#### How should this be manually tested?

Create a formfield using `Select` as component and setting `options` prop.

#### Is this change backwards compatible or is it a breaking change?

Backwards compatible

### CODE REVIEW

**Comment by ShimiSun** [comment]
Moving thread from slack:

```
oorestisime  [1 day ago]
Hm i think this will be problematic since it will override and add typings to the formfield that are not there always ( imagine formfield eith checkbox) i am not ts expert so not sure how this should be handled properly


rogie500  [22 hours ago]
Agreed. I tried passing `Select` component as a child node but the issue is it doesnt bind the value of it to the Form state.  So I miss out on the `onSubmit` functionality of the form (edited)

oorestisime  [17 hours ago]
Ok lets discuss this over in the PR it will be easiee :)
```

**Comment by roger-king** [comment]
Would it possibly be better to be able to pass the component as a child component and set the value of the child component in the context  of the form component?

**Comment by roger-king** [comment]
@ShimiSun Would something like this work? `JSX.IntrinsicAttributes['select']`

**Comment by oorestisime** [comment]
I think this is not the way to go either (intrinsic elements) since the attrs of select are not the same with an input. i think we discussed similar (or the same) issues in an another PR which i can't find. Not sure how to best solve this issue, i am not ts ninja :( will try to search a bit

**Comment by pakdev** [comment]
So is no one using Typescript with FormFields/Selects? It seems like the only logical solution is to create specialized FormFields e.g. SelectFormField, InputFormField, ...

**Comment by roger-king** [comment]
@pakdev 
What I have done is create a new formfield component and handle the state on my own.

**Comment by ShimiSun** [comment]
Closing due to a stale situation, the original issue #3370 is still opened to be tracked.

**Pull request closed without merging**
