### PR TITLE
Make Storybook Example Titles Capitalization Consistent

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?
This PR capitalizes storybook examples into 'Title Case' and renames some stories to clearer names.

#### Where should the reviewer start?
src/js/components/Accordion/stories/Simple.js

#### Any background context you want to provide?
There isn't consistency in how storybook examples were capitalized. This PR aims to establish a style guide that storybook examples should be in title case (first letter of each word capitalized).

#### Do the grommet docs need to be updated?
No.

#### Should this PR be mentioned in the release notes?
No.

#### Is this change backwards compatible or is it a breaking change?
Yes, this is backwards compatible.

### CODE REVIEW

**Comment by ShimiSun** [comment]
Thank you for working on this, I'm not sure if capitalizing is the right approach, why do you think it is better than how it is today?
I'm looking at the storybook official example, and it doesn't look capatalized to me https://storybooks-official.netlify.com/?path=/story/ui-panel--default

**Comment by taysea** [comment]
I guess that the aim of this PR was more to propose consistency in the way storybook examples are named because in ours, some stories are in title case 'Story Example' and others are like 'Story example'. Maybe capitalizing everything isn't the perfect solution (I'm very open to other options), but I think some discussion about a style guide for story naming could be beneficial moving forward. 

Some concepts for discussion could be:
- If a storybook example is the name of the prop, do we leave lowercase to match how it would be typed in code? (`border` or `onChange` as opposed to `Border` or `OnChange`)
- If a storybook is combining multiple props or concepts, what punctuation do we use to indicate this? (`Controlled and Grouped` or `Controlled & Grouped` or `Controlled, Grouped` or `Controlled + Grouped`)

I could open this as a discussion issue if you think it's fitting. These changes don't affect how the code works, but I think consistency in naming conventions would make for a smoother user experience and create a more polished look.

**Comment by ShimiSun** [comment]
agreed.
I'm inclining to follow the standards of https://storybooks-official.netlify.com/?path=/story/ui-panel--default.

Feel free to open for a discussion.

**Comment by ShimiSun** [comment]
I'm just dropping a comment here so I won't forget, I noticed on storybook ^5.2 the title case behavior on storybook UI stories is enforced out of the box.

**Comment by ShimiSun** [comment]
linking to #3212

**Comment by ShimiSun** [comment]
We came to a resolution that all stories should use sentence case.

**Pull request closed without merging**
