### PR TITLE
Modified FormField TypeScript properties to extend from input element instead of div

### PR DESCRIPTION
**Pull request by dannycalleri**
#### What does this PR do?

This PR solves [this issue](https://github.com/grommet/grommet/issues/2887) and it should be pretty straightforward, let me know if you need any help.
Additionally, I updated some snapshots since tests were failing.

### CODE REVIEW

**Comment by oorestisime** [comment]
tests shouldn't be failing. at least they don't on master. did you use yarn or npm for installing dependencies? because we currently don't have a package-lock.json you might not have gotten the correct dependencies.

**Comment by dannycalleri** [comment]
Ok I see, I used npm. Tests where passing with `npm run test`.

**Comment by oorestisime** [comment]
` rm -r node_modules && yarn install` and then `yarn test` on master yields no issues for me.

**Comment by dannycalleri** [comment]
Thanks for your help @oorestisime , I removed `package-lock.json`, `node_modules` and everything is working fine with old snapshots, switched back to them.

**Pull request merged**
