### PR TITLE
fix selectMultiple + search

### PR DESCRIPTION
**Pull request by romanalesenkov1**
#### What does this PR do?
https://github.com/grommet/grommet/issues/2961
Previously it was impossible to select multiple values using search. Fix this case.

The problem was that options change when they are filtered using search. So indexes of selected values are invalid. Now we always use the initial list of options, so the indexes will always be valid.

#### What testing has been done on this PR?
tested selecting multiple values using search and without using search
#### How should this be manually tested?
```
       <Select
          size="medium"
          placeholder="Select"
          multiple
          value={value}
          options={options}
          closeOnChange={false}
          onChange={({ value: nextValue }) => setValue(nextValue)}
          onClose={() => setOptions(defaultOptions)}
          onSearch={text => {
            const escapedText = text.replace(/[-\\^$*+?.()|[\]{}]/g, '\\$&');
            const exp = new RegExp(escapedText, 'i');
            setOptions(defaultOptions.filter(o => exp.test(o)));
          }}
        />
```

e.g. storybook

- simple selection
- searching and then select stores correct values
- multiple select with/without searching
- selecting already selected in multiple select removes the selection
#### What are the relevant issues?
https://github.com/grommet/grommet/issues/2961

#### Do the grommet docs need to be updated?
No
#### Is this change backwards compatible or is it a breaking change?
No

### CODE REVIEW

**Review by ShimiSun — APPROVED** [review]
Nicely done, works as expected! 
I added a story example so it will more straightforward to have sanity checks on the serach+multiple scenario in the future, the story demonstrates the behavior as expected. Thank you for your contribution! 💟

**Comment by ericsoderberghp** [comment]
I think something isn't quite right. Consider this sequence:
1. click to open -> drop opens
2. type "2" -> options are pruned
3. click "option 2" -> value shows "option 2", drop is closed
4. click to open -> drop opens, showing "option 2" selected
5. type "3" -> options are pruned, BUT: value shows "option 13"

If I have no value, or if I have multiple options selected already, the search + drop + value all behave well. But if I have one option selected and then perform a search, the visible value is being changed incorrectly.

**Review by ericsoderberghp — APPROVED** [review]

**Comment by ericsoderberghp** [comment]
Thanks for your contribution!

**Comment by ShimiSun** [comment]
Right on time for the release! Thank you @romanalesenkov1!

**Comment by romanalesenkov1** [comment]
Thank you guys!

**Pull request merged**
