### PR TITLE
Added tests for Chart utils

### PR DESCRIPTION
**Pull request by shabtaisharon**
#### What does this PR do?
Added tests for Chart utils
#### Where should the reviewer start?
`src/js/components/Chart/__tests__/utils-test.js`
#### What testing has been done on this PR?
`yarn test`
#### How should this be manually tested?
`yarn test`
#### Any background context you want to provide?
No
#### What are the relevant issues?
#4539
#### Screenshots (if appropriate)
Screen Shot 2020-10-19 at 4 16 59 PM
Screen Shot 2020-10-19 at 4 15 46 PM
#### Do the grommet docs need to be updated?
No
#### Should this PR be mentioned in the release notes?
No
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Comment by ShimiSun** [comment]
Those two functions are not being used by grommet-core, I'm wondering if the better approach to increase the coverage and add simplicity will be to simply remove those functions without needing the tests. @ericsoderberghp, any chance users will be using those functions? we do not publish those externally and I'm inclining to simply remove them.

**Comment by ericsoderberghp** [comment]
Agreed that we aren't using them internally. And, we don't document them. However, we are exporting them. So, someone could be using them. I'm wondering if we should add a `console.warn()` to say that they will be removed and ask people to get in touch with us if they have concerns.

**Comment by shabtaisharon** [comment]
> Agreed that we aren't using them internally. And, we don't document them. However, we are exporting them. So, someone could be using them. I'm wondering if we should add a `console.warn()` to say that they will be removed and ask people to get in touch with us if they have concerns.

@ericsoderberghp I've updated my PR

**Review by ShimiSun — APPROVED** [review]
Thanks! 🎉

**Pull request merged**
