### PR TITLE
fix for SelectMultiple when using object values inline clicks

### PR DESCRIPTION
**Pull request by urubatan**
When clicking on an inline option for a SelectMultiple that uses objects as options the behavior should be the same as when the options are strings.
This PR fixes the comparison for object values to be the same as for string values

#### What does this PR do?
changes one line in SelectMultipleValue to make sure the inline option clicked is deselected instead of being the only one selected for object options

#### Where should the reviewer start?
you can check the current error in storybook 

https://storybook.grommet.io/?path=/story/input-selectmultiple-object-options--object-options

when clicking in any inline option that is the only one that is still selected, instead of deselecting only that option

#### What testing has been done on this PR?
I tested manually on my machine

all existing tests are still working

I didn't add more tests to confirm the bug because my javascript skills aren't good enough and I didn't know how to do that

#### How should this be manually tested?

opening the storybook for this PR you can verify the correct behavior 

#### What are the relevant issues?

This PR fixes the issue #6737 

#### Do the grommet docs need to be updated?

No, after this PR the docs are correct for all cases

#### Should this PR be mentioned in the release notes?

no need

#### Is this change backwards compatible or is it a breaking change?

it just fixes a bug

### CODE REVIEW

**Review by jcfilben — COMMENTED** [review]
Thanks for fixing this! Would you be willing to add a unit test for this?

**Comment by urubatan** [comment]
Sure, I'll check how to and will push the tests later today

Em qui., 6 de abr. de 2023 17:37, Jessica Filben ***@***.***>
escreveu:

**Comment by jcfilben** [comment]
> Sure, I'll check how to and will push the tests later today

Thanks! Feel free to reach out if you run into any issues

**Comment by urubatan** [comment]
@jcfilben just pushed the test to validate the fix

**Review by jcfilben — APPROVED** [review]
Nice work!

**Review by taysea — APPROVED** [review]

**Pull request merged**
