### PR TITLE
Fix click respond outside of visible area in checkbox and radiobutton

### PR DESCRIPTION
**Pull request by IvanFrescas**
#### What does this PR do?
Fix issue #3605 Checkboxes respond to clicks outside of visible area

#### Where should the reviewer start?
js/components/Checkbox/StyledCheckBox

#### What testing has been done on this PR?
Storybook

#### How should this be manually tested?
Using checkbox component as shown in the following link https://codesandbox.io/s/grommet-v2-template-xnmqs

#### Any background context you want to provide?
If you click outside the checkbox the state changes

#### Screenshots (if appropriate)
Actual Behavior
ezgif com-video-to-gif

Solution
ezgif com-video-to-gif

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
No

### CODE REVIEW

**Comment by ShimiSun** [comment]
Hi buddy! thank you for the contribution, can you please run `yarn test-update` and push the new snapshots?

**Comment by IvanFrescas** [comment]
Ready, I've updated them. 🙂

**Comment by iMerica** [comment]
LGTM +1 👍

**Comment by iMerica** [comment]
Looks like this can be merged now. Can you update your branch @IvanFrescas ?

**Comment by IvanFrescas** [comment]
I just updated the branch, thank you.

**Comment by iMerica** [comment]
👍 cc/ @ericsoderberghp

**Comment by ShimiSun** [comment]
Thank you for your contribution @IvanFrescas !

**Pull request merged**
