### PR TITLE
PageHeader allow title to wrap instead of overflow

### LINKED ISSUE #6295: PageHeader heading with long string overflows rather than breaking
### Expected Behavior

Headings containing user generated content are unpredictable and can be quite lengthy. A long string passed as a heading to PageHeader should wrap when it runs out of space.

### Actual Behavior

PageHeader's heading overflows and collides with other content.

### URL, screen shot, or Codepen exhibiting the issue

Screen Shot 2022-08-23 at 10 50 21 AM

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: v2.25.1
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by halocline**
#### What does this PR do?

Closes #6295 by:
- Adds `overflowWrap` prop to Heading which accepts any valid `overflow-wrap` CSS.
- Updates PageHeader implementation to wrap instead of overflow.

Also, for backwards compatibility, ensures Calendar Header overflows instead of wrapping which is its current behavior.

#### Where should the reviewer start?

Heading.js

#### What testing has been done on this PR?

Jest suite, Storybook, plus added snapshot test.

#### How should this be manually tested?

Lengthy word(s) within Heading and PageHeader.

```
<Heading>bluevelvet.aixncc.ig.acmecorp.com</Heading>
<Heading overflowWrap="break-word">
    bluevelvet.aixncc.ig.acmecorp.com
</Heading>
<PageHeader>
    title="bluevelvet.aixncc.ig.acmecorp.com"
    actions={[<Button label="click me" />]}
/>
```

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [x] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?

#6295

#### Screenshots (if appropriate)
Screen Shot 2022-08-23 at 2 14 17 PM

Screen Shot 2022-08-23 at 2 15 14 PM

#### Do the grommet docs need to be updated?

No. Proposing the `overflowWrap` be internal only and undocumented for now unless others feel like it would be valuable to document.

#### Should this PR be mentioned in the release notes?

Yes.

#### Is this change backwards compatible or is it a breaking change?

Backwards compatible.

### CODE REVIEW

**Review by taysea — APPROVED** [review]
LGTM!

**Comment by ericsoderberghp** [comment]
I'm wondering if we should always have a wrap. Is there ever a rationale to not break at all? Could we default to `break-word` and detect if this isn't enough and automatically switch to `anywhere`? That way the caller doesn't have to do anything, since it could be difficult to predict which one to use since it might depend on translations, user data, and resolution.

**Comment by halocline** [comment]
> I'm wondering if we should always have a wrap. Is there ever a rationale to not break at all? 

I having a hard time coming up with a rationale, and definitely not one that wouldn't be an edge case. If there were one, the caller would have `overflowWrap="normal"` or `truncate` as options.

> Could we default to `break-word` and detect if this isn't enough and automatically switch to `anywhere`? That way the caller doesn't have to do anything, since it could be difficult to predict which one to use since it might depend on translations, user data, and resolution.

I would be okay with defaulting to `break-word`. What's the mechanism for detecting where `break-word` is not enough?

**Comment by ericsoderberghp** [comment]
> > I'm wondering if we should always have a wrap. Is there ever a rationale to not break at all?
> 
> I having a hard time coming up with a rationale, and definitely not one that wouldn't be an edge case. If there were one, the caller would have `overflowWrap="normal"` or `truncate` as options.

This seems infrequent enough to me to not need to formalize it as a property.

> > Could we default to `break-word` and detect if this isn't enough and automatically switch to `anywhere`? That way the caller doesn't have to do anything, since it could be difficult to predict which one to use since it might depend on translations, user data, and resolution.
> 
> I would be okay with defaulting to `break-word`. What's the mechanism for detecting where `break-word` is not enough?

I was envisioning comparing offset width and scroll width in some manner.

**Review by ericsoderberghp — DISMISSED** [review]

**Comment by ericsoderberghp** [comment]
This seems like a notable regression

Screen Shot 2022-09-02 at 2 50 46 PM

**Review by taysea — APPROVED** [review]
LGTM! Thanks for fixing the calendar one.

**Comment by halocline** [comment]
> This seems like a notable regression
> 
> Screen Shot 2022-09-02 at 2 50 46 PM

Addressed. Set Calendar Heading to use `overflowWrap="normal"` for backwards compatibility.

**Review by ericsoderberghp — APPROVED** [review]

**Pull request merged**
