### PR TITLE
Changed Button to make Kind and size work together (#4134)

### PR DESCRIPTION
**Pull request by sabarnix**
#### What does this PR do?

This PR fixes a bug in Button component due to which Size and Kind (primary, secondary) won't work together. For KindButton the padding values are being read from a `theme.button.size[size].padding` path, which is not present in the theme.

#### Where should the reviewer start?

src/js/components/Button/StyledButtonKind.js

#### How should this be manually tested?

create a theme with button kind (default, primary) definitions in theme

#### What are the relevant issues?

https://github.com/grommet/grommet/issues/4134

#### Do the grommet docs need to be updated?
no

#### Should this PR be mentioned in the release notes?
no

#### Is this change backwards compatible or is it a breaking change?
yes

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
The StyledButtonKind changes look good to me.
The MaskedInput snapshot change seems unrelated. Is your node_modules up to date?

**Comment by sabarnix** [comment]
I cloned the repo today and made a fresh install. Even I am not sure why the snapshot for MaskedInput changed. Will try to investigate later today

**Comment by sabarnix** [comment]
I have removed the snapshot change from merge request. But it seems like running test on a fresh setup fails on MaskedInput snapshot

**Comment by ShimiSun** [comment]
Thank you for your contribution! The fix will be available on the next release.

**Pull request merged**
