### PR TITLE
DataTable - add step support for onMore loading

### PR DESCRIPTION
**Pull request by ShimiSun**
#### What does this PR do?
DataTable - add step support for onMore loading
#### Where should the reviewer start?
doc.js
#### What testing has been done on this PR?
logs
#### How should this be manually tested?
datatable
#### What are the relevant issues?
#3063 
#### Do the grommet docs need to be updated?
yep, done
#### Should this PR be mentioned in the release notes?
yes
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Comment by oorestisime** [comment]
lgtm. i am wondering if we really need to have this in the theme though.
- doesn't  look to affect styling
- i doubt all the datatables in an application would need the same step.

**Comment by ericsoderberghp** [comment]
> lgtm. i am wondering if we really need to have this in the theme though.
> 
> * doesn't  look to affect styling
> * i doubt all the datatables in an application would need the same step.

Agreed

**Comment by ShimiSun** [comment]
@ericsoderberghp I've found more similarity of the DataTable`step` behavior to Select rather than InfiniteScroll. 
Select & DataTable has the InfiniteScroll embedded and not exposed, and on that note, Select is consuming the step value via the theme the same way as I implemented it for DataTable.
https://github.com/grommet/grommet/blob/001cd59bc1ee792019a88646589fd223c87e2cdb/src/js/components/Select/SelectContainer.js#L393

**Comment by ericsoderberghp** [comment]
I see. So, we are already inconsistent, between how InfiniteScroll and Select handle the default value for step. I just tend to agree with @oorestisime in that I'm having a hard time seeing how the default value for step related to theming.

**Comment by ShimiSun** [comment]
@oorestisime & @ericsoderberghp, I appreciate your feedback guys! unless you advise otherwise, I'll be closing this PR and we'll work on a new `step` prop for DataTable to make the behavior consistent with InfiniteScroll rather than Select.

**Pull request closed without merging**
