### PR TITLE
Added functionality to handle new searched value

### PR DESCRIPTION
**Pull request by nik72619c**
Added functionality to handle new searched value

#### What does this PR do?
this solves issue #3248. it detects the enter key and for now, an alert box popover is displayed. 

#### Where should the reviewer start?
The reviewer should start from the file Search.js. The Select component inside it now has an onkeypress event.

#### What testing has been done on this PR?
The manual forms of testing like breaking change detections etc are checked. It is ensured that the existing code does not break

#### How should this be manually tested?
The search select component inside the storybook examples consist of a search select dropdown. It can be tested by typing an option and then clicking enter.

#### Any background context you want to provide?
No

#### What are the relevant issues?
None

#### Screenshots (if appropriate)
nik1234

#### Do the grommet docs need to be updated?
Yes

#### Should this PR be mentioned in the release notes?
Yes

#### Is this change backwards compatible or is it a breaking change?
Yes

### CODE REVIEW

**Comment by juanlanus** [comment]
IMO there should be at least a ^Z option just after having added the new list item in case the user realizes just after enter that there is a typo (as usually happens). 
Consider opening a new issue to enable deleting items from the list using the keyboard or with the mouse/finger hitting an [x] button shown only at the end of the selected/hovered choice. 
This is to follow the rule that says that the user must be allowed to undo everything (almost) so she can use the UI without the fear of introducing an irreversible unrecoverable fatal modification in the data.

**Comment by ShimiSun** [comment]
@nik72619c hi buddy! thanks for working on this.
I'm running the deployment of your PR https://deploy-preview-3430--sad-tereshkova-173d07.netlify.com/?path=/story/select--search and I don't get the alert as you described.
I've opened the Select component on storybook -> Search -> typed 'shimi' as a string and Enter, but nothing happened. what am I missing?

**Comment by nik72619c** [comment]
I'll just look into it

**Comment by nik72619c** [comment]
main
The build seems to work fine in my case .
I believe its because you didnt enter a valid option which was present in the list.

**Comment by ShimiSun** [comment]
I've done some clean-ups on this PR and I think it is good to go, @ericsoderberghp I'll appreciate your second review.

**Comment by ShimiSun** [comment]
I think we already took care of this functionality, @IanKBovard can you please verify it already exists so we can close this PR?

**Comment by IanKBovard** [comment]
@nik72619c just double checking the intention of this pr. It's to add enter key functionality to the select component? If that's the case, we can close this pr.

**Comment by IanKBovard** [comment]
@nik72619c I know it's been a while, just checking in to see where you are with this pr.

**Comment by ShimiSun** [comment]
I'll be closing this PR since I think we already approached a fix elsewhere, feel free to reopen if still relevant.
Thank you!

**Pull request closed without merging**
