### PR TITLE
Storybook Component Story Format - Layout

### PR DESCRIPTION
**Pull request by minicrashxv**
#### What does this PR do?
Storybook component story format on Layout category 
#### Where should the reviewer start? 
src/js/components/Box 
src/js/components/Card
src/js/components/Footer
src/js/components/Grid
src/js/components/Header
src/js/components/Layer
src/js/components/Main
src/js/components/Sidebar
src/js/components/Stack 
#### What testing has been done on this PR?
See hierarchy on storybook and jest tests
#### How should this be manually tested?
Launch storybook and see Layout part in sidebar
#### Any background context you want to provide?
no
#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
no
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Comment by leossantiago** [comment]
I believe this is related to #4651 so I'll just link it here so it shows as mentioned.

Nice work! A maintainer will be able to correct me if I'm wrong, but I'd suggest you take a look at PR #4654.
Right now, you just renamed component titles in the sidebar:

image

e.g. you should replace `storiesOf('Accordion', module).add('Custom', () => <CustomAccordion />);` with `export const Custom = () => <CustomAccordion />;` on each story, as shown in #4654. It looks like you should also create a `stories/ComponentName.stories.js` file like this:

```
export { Custom } from './Custom';
export { Header } from './CustomHeader';
export { Rich } from './typescript/Rich.tsx';
export { Simple, DarkNoAnimation, Multiple } from './Simple';

export default {
  title: 'Controls/Accordion',
};
```

@ShimiSun suggested that PRs should be per component regarding this update, but she'll be able to talk further about that. Since you already started working, I believe you might continue working on this PR, but you'll have A LOT of work updating so many components at once.

Also noticed this is your first PR ever. Welcome aboard :) 

Let me know if you need help following the format. Good luck!

**Comment by minicrashxv** [comment]
Thant for your response ! 
First my storybook looks like this : 
storybook stories component format

I correct components as you show me. 
However PRs per component, there will be a lot of PR. That's why I would make PR per category component (Layout, Type Controls ...)

I'm really proud to work on grommet for my first contributing open source, I use this project yet !

**Comment by leossantiago** [comment]
Now that's weird.
Could you please check if your local branch is even with your fork? Because you merged branch 'master' into yours, and it looks like this brought some changes from the mentioned PR to your branch, and it might be the reason we see different storybook layouts. 

Source: https://github.com/minicrashxv/grommet/commit/59b79c6df0a39f57db111c417f69fc672dd1ec79

**Review by jcfilben — COMMENTED** [review]
Congratulations on your first PR! As @leossantiago mentioned above, the way the PR is set up currently the stories will appear as `Layout | Grid`. If you updated the stories to look like this:
image
Then make sure you push your local changes up to the remote branch so the PR is up to date with the changes you are making.

**Comment by ShimiSun** [comment]
Linking #4651

**Comment by ShimiSun** [comment]
Hi buddy, any updates on the progress on this PR? There are a lot of great examples of the related issue to complete the CSF migration.

**Comment by ShimiSun** [comment]
I'll be closing this PR due to its conflicts, feel free to file a more relevant PR or update the current, thank you!

**Pull request closed without merging**
