### PR TITLE
Fix onwheel freezing pages (fixes #979); add FeatureDetects.js

### LINKED ISSUE #979: Pages with Carousel freezes after scrolling or being unfocused.
### Expected Behavior
A page with a Carousel should scroll smoothly anytime after being unfocused

### Actual Behavior
The page freezes ( in chrome at least)
With this warning being displayed in the console:

> Handling of 'wheel' input event was delayed for 8845 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.

### URL, screen shot, or Codepen exhibiting the issue

After trying on my own page I went back to main site and sure enough, the behavior was the same.
https://grommet.github.io/docs/carousel/

### Steps to Reproduce
 1. open 2 tabs in chrome, (Tab1 = https://grommet.github.io/docs/carousel/,   Tab2 = empty page)
 2. scroll up and down on Tab1
 3. switch to Tab2 
 4. go back to Tab1 and try to scroll again ( warning in console should be displayed and UI frozen)

### Your Environment

* Grommet version: v1.0.0
* Browser Name and version: Google Chrome  Version 53.0.2785.116 (64-bit)
* Operating System and version (desktop or mobile): OSX Yosemite  10.10.5

### PR DESCRIPTION
**Pull request by davidcalhoun**
#### What does this PR do?
Adds a fix to Tiles which prevents certain pages from freezing up, especially when a page is refocused after switching to a different browser tab.

This is also the initial commit of `util/FeatureDetect.js`, which is a central place to store browser feature detects.

#### What testing has been done on this PR?
Tested in OSX Chrome 54 and Windows 8.1 IE 11.

#### How should this be manually tested?
See #979 and attached gifs (below).

#### Any background context you want to provide?
https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

#### What are the relevant issues?
#979 

#### Screenshots (if appropriate)
Before:
before-min

After:
after-min

#### Do the grommet docs need to be updated?
No

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

**Comment by alansouzati** [comment]
Interesting I was not able to reproduce this issue in my local environment.

Can you try to use passive all the time and test with out supported browsers? I'm wondering if we can set that option always, and a avoid creating an empty div to get passive function.

**Comment by davidcalhoun** [comment]
For older browsers that don't support passive events, it looks like they interpret the third argument (useCapture) as "true" because an object is truthy (e.g. `!!{};  // true`), so these will be equivalent:

`document.addEventListener('wheel', function(){}, {passive: true});`
`document.addEventListener('wheel', function(){}, true);`

I was worried about always setting useCapture to `true`, but it looks like for the `wheel` event, it doesn't seem to matter whether it's set to `true` or `false`.  Both the code snippets above work in these browsers (tested by adding a console.log to the function):

* Firefox 49.0.1 OSX
* Safari 9.1.3 OSX
* IE9 Windows 7
* IE11 Windows 8
* Chrome 54

I can take out the feature test for now.  Not sure if passive events will ever be needed in combination with setting useCapture to `false`, but for now it looks like it's not needed.

**Comment by alansouzati** [comment]
I agree with removing this and leave passive true always.

**Comment by davidcalhoun** [comment]
Sounds good!  I removed FeatureDetects and also simplified the code as discussed above.

Retested and verified working on the following:
*Chrome 54 OSX
*Firefox 49.0.1 OSX
*IE11 Windows 8
*Safari 9.1.3 OSX

**Comment by alansouzati** [comment]
would you mind squashing your commits?

I'm trying to avoid messages like this in your commit history:

Merge remote-tracking branch 'upstream/master' into fix-onwheel-freezing

**Comment by davidcalhoun** [comment]
@alansouzati Ok will do!  I tried a `git rebase` to squash the commits, but it looks like that didn't give me the desired effect.  I'm going to open up a new PR.

**Comment by davidcalhoun** [comment]
Opened up PR #1000 to keep the history clean

**Pull request closed without merging**
