### PR TITLE
Refactored TextInput story in FormField using Hooks

### PR DESCRIPTION
**Pull request by thidasapankaja**
#### What does this PR do?
Refactor `src/js/components/FormField/stories/TextInput.js` using Hooks

#### Where should the reviewer start?
`src/js/components/FormField/stories/TextInput.js`

#### What testing has been done on this PR?
Running `yarn test`

#### How should this be manually tested?
Running `yarn test`

#### Any background context you want to provide?
N/A

#### What are the relevant issues?
https://github.com/grommet/grommet/issues/3394

#### Screenshots (if appropriate)
N/A

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
No

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

**Comment by ShimiSun** [comment]
Verified with https://www.chromaticqa.com/build?appId=5d7a63beda813e00202faf9d&number=34.

**Comment by ShimiSun** [comment]
Awesome!! thanks for keeping up! 🎉

**Comment by thidasapankaja** [comment]
In the latest build of the project, there're multiple tests failing.

**Comment by ShimiSun** [comment]
@thidasapankaja thanks for letting us know, I just ran the tests locally and it all passed. make sure you are using a clean fork.
We wouldn't be able to merge a PR that is breaking the test, so I will be surprised if it actually happened.

**Pull request merged**
