### PR TITLE
Add selected theme property for DataTable (#7343)

### LINKED ISSUE #7343: DataTable -- add `theme.dataTable.body.selected`
### Is this something you or your team is interested in contributing a pull request towards?

Yes.

### Expected Behavior

Should be able to theme the background color for body cells when their row is selected. Open to discussion of theme object structure.

### Actual Behavior

No theme option.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by miqh**
#### What does this PR do?

It introduces support for recognising an additional theme property to customise the background colour of selected records in the DataTable component.

#### Where should the reviewer start?

The proposed schema extension to DataTable related theme properties, then onward to the DataTable source.

#### What testing has been done on this PR?

I've added three new snapshot tests for DataTable covering the cases where I saw selected record styling being pertinent.

#### How should this be manually tested?

Ensure that the new theme property is set and that a DataTable is configured to support selection.

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [x] `asFragment()` is used for snapshot testing.

#### Any background context you want to provide?

None.

#### What are the relevant issues?

Closes #7343.

#### Screenshots (if appropriate)

I've modified some DataTable stories to illustrate the visual scope of the new theme property.

Single row selection:

image

Grouped row selection:

image

Row detail parent selection:

image

#### Do the grommet docs need to be updated?

Yes, should indicate the avaiability of this new theme property.

#### Should this PR be mentioned in the release notes?

Probably, for maintainers to decide.

#### Is this change backwards compatible or is it a breaking change?

The new theme property isn't set by default, so it shouldn't be a breaking change.

### CODE REVIEW

**Review by taysea — COMMENTED** [review]
Thank you for this PR, looking great! @halocline would you agree with the logic proposed in this PR that "selected" row styling would win over "pinned"?

My thinking is yes it should, but wanted to double check your thoughts.

**Comment by halocline** [comment]
> Thank you for this PR, looking great! @halocline would you agree with the logic proposed in this PR that "selected" row styling would win over "pinned"?
> 
> My thinking is yes it should, but wanted to double check your thoughts.

Yes, I agree.

**Review by halocline — APPROVED** [review]
Looks great. Thank you for your contribution and thoroughness including tests, @miqh .

**Review by taysea — APPROVED** [review]
LGTM, thank you for the contribution!

**Pull request merged**
