### PR TITLE
Type definition for Drop and DropButton event handlers

### PR DESCRIPTION
**Pull request by jimenezff**
#### What does this PR do?
Event handler types for Drop and DropButton

#### Where should the reviewer start?
`src\js\components\Drop\index.d.ts`
https://github.com/grommet/grommet/blob/51fb24adf2f7009a12c94ed57d4afedb56c5a86b/src/js/components/Drop/DropContainer.js#L273

`src\js\components\DropButton\index.d.ts`
https://github.com/grommet/grommet/blob/51fb24adf2f7009a12c94ed57d4afedb56c5a86b/src/js/components/DropButton/DropButton.js#L73 https://github.com/grommet/grommet/blob/51fb24adf2f7009a12c94ed57d4afedb56c5a86b/src/js/components/DropButton/DropButton.js#L81

#### What testing has been done on this PR?
Tests: src\js\components\DropButton\__tests__\DropButton-test.js

#### How should this be manually tested?
The referenced lines above and tests should be enough

#### What are the relevant issues?
#3165 

#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
no
#### Is this change backwards compatible or is it a breaking change?
compatible

### CODE REVIEW

**Comment by ShimiSun** [comment]
@jasnross can you help with another pair of eyes on this PR buddy?

**Review by jcfilben — COMMENTED** [review]
Looks good, I tested using storybook stories. From what I can tell OnClickOutside is working (tested in Multiple and Progressive stories). I also tested onClose and onOpen and those both seem to be working as well (tested with Simple and Calendar DropButton stories). I also looked over the jest tests and those are looking good

**Comment by jimenezff** [comment]
Thanks @jcfilben

**Comment by ShimiSun** [comment]
Thank you for your contribution!

**Pull request merged**
