### PR TITLE
Adding testcafe

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
This PR adds the base work for the e2e testing files to Grommet. 
We can now run `yarn start` that will bring up another local host from which we will have our testing located. 
We can run `yarn test-e2e` which will run the test cafe tests that we will create 
#### Where should the reviewer start?
in the app folder
#### What testing has been done on this PR?
locally
#### How should this be manually tested?
locally 
#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### Any background context you want to provide?
Also added packages that we will need for testcafe for example 
`@testing-library/testcafe`
in which we can use the best practices to get elements by using screen for querying

#### What are the relevant issues?
closes https://github.com/grommet/hpe-design-system/issues/2780
#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
maybe
#### Is this change backwards compatible or is it a breaking change?
 backwards compatible

### CODE REVIEW

**Comment by britt6612** [comment]
Adding a command to run localhost and run tests..

**Review by jcfilben — COMMENTED** [review]
We should exclude the app folder from the distribution (See `build` command line 31 of package.json)

**Comment by ericsoderberghp** [comment]
I'm wondering whether the top level directory should be "app" or "test". "test" might be more indicative of its purpose and prevent us from feeling like its main goal is to be a well rounded "app" example. This might give us more freedom to do oddball things that we want to test without feeling like they have to be good examples for building apps.

**Comment by britt6612** [comment]
> I'm wondering whether the top level directory should be "app" or "test". "test" might be more indicative of its purpose and prevent us from feeling like its main goal is to be a well rounded "app" example. This might give us more freedom to do oddball things that we want to test without feeling like they have to be good examples for building apps.

Im wondering if maybe we should name it Grommet-Tests or component tests then move the `test` folder into that subfolder. That way we don't have 2 folders that are both tests

**Comment by jcfilben** [comment]
> Im wondering if maybe we should name it Grommet-Tests or component tests then move the test folder into that subfolder. That way we don't have 2 folders that are both tests

Maybe something in the name to signify that this space if for end to end testing as apposed to unit testing.

**Comment by taysea** [comment]
> > Im wondering if maybe we should name it Grommet-Tests or component tests then move the test folder into that subfolder. That way we don't have 2 folders that are both tests
> 
> Maybe something in the name to signify that this space if for end to end testing as apposed to unit testing.

`/e2e` ?

**Comment by ericsoderberghp** [comment]
> > > Im wondering if maybe we should name it Grommet-Tests or component tests then move the test folder into that subfolder. That way we don't have 2 folders that are both tests
> > 
> > 
> > Maybe something in the name to signify that this space if for end to end testing as apposed to unit testing.
> 
> `/e2e` ?

would work well with `yarn start-e2e` and `yarn test-e2e`

**Comment by halocline** [comment]
> `/e2e` ?

☝️ was my initial reaction as well.

Would the directory structure then be? (e.g. app and tests nested under e2e):
/coverage
/dist
/e2e
  /app
  /tests
...
/src
/storybook
/tools

**Comment by ericsoderberghp** [comment]
> > `/e2e` ?
> 
> ☝️ was my initial reaction as well.
> 
> Would the directory structure then be? (e.g. app and tests nested under e2e): /coverage /dist /e2e -- /app -- /tests ... /src /storybook /tools

I was thinking paralleling a typical app:
/e2e
-- /public
-- /src
-- /webpack.config.js
-- /test

**Comment by ericsoderberghp** [comment]
Can the e2e test configuration be inside "app", since they go together?

**Review by ericsoderberghp — APPROVED** [review]
Seems like a reasonable place to start.

**Review by jcfilben — APPROVED** [review]
Looks good!

**Pull request merged**
