### PR TITLE
Tasmania in World Map

### PR DESCRIPTION
**Pull request by jimenezff**
#### What does this PR do?
Adds Tasmania to World Map component
#### Where should the reviewer start?
WorldMap Storybook
#### What testing has been done on this PR?
Snapshot update
#### How should this be manually tested?
n/a
#### Any background context you want to provide?
n/a
#### What are the relevant issues?
n/a
#### Screenshots (if appropriate)
image

#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
no
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Comment by ShimiSun** [comment]
Thank you for the PR.
I'm curious to know what sources have you used to decide how many dots on the map Tasmania should have assigned.

**Comment by jimenezff** [comment]
I just compared, by eye, the dimensions of the existing size of Australia (10 dots wide) and New Zealand (3 dots). I'd be happy to make any changes.

**Comment by jimenezff** [comment]
To illustrate, this is the what I mean 
image

**Comment by ericsoderberghp** [comment]
I'm open to this change. One thing I'd suggest is verifying that adding a `place` that has a latitude and longitude in Tasmania shows up in the same dot.

**Comment by jimenezff** [comment]
I did verify that but I should have send that along with the PR... 

I can try it again in a few hours and send screenshots. Or would it be more acceptable to modify an existing story to include Tasmania?

**Comment by ShimiSun** [comment]
I think some screenshots (code/UI) to demonstrate it works will be helpful.

**Comment by jimenezff** [comment]
Screenshots for 3 different coordinates:

https://goo.gl/maps/bfAVKxubggDS8Y5k6
image
___
___

https://goo.gl/maps/p7bHiu7f2LASRiP29
image
___
___

https://goo.gl/maps/d7YCPoNvqTL3Rdfu6
image

**Comment by ShimiSun** [comment]
Thank you for your contribution!

**Pull request merged**
