### PR TITLE
changes Collapsible children visibility according to its state

### LINKED ISSUE #4498: Collapsible allows user to tab focus on focusable children when not open
### Expected Behavior

When Collapsible is not open, user should not be able to tab focus on any focusable children within the Collapsible.

### Actual Behavior

User is able to tab focus on focusable children within the Collapsible.

### URL, screen shot, or Codepen exhibiting the issue

[Code Sandbox](https://codesandbox.io/s/compassionate-goldwasser-u60d0?file=/index.js)

### Steps to Reproduce

1. Create Collapsible with focusable element inside, e.g. Button.
2. While Collapsible is not open, attempt to tab focus.
3. Observe focus on focusable element inside of Collapsible, instead of the next focusable element outside of the Collapsible.

### Your Environment

- Grommet version: 2.15.0
- Browser Name and version: Firefox Developer Edition 81.0b3
- Operating System and version (desktop or mobile): MacOS Catalina 10.15.6

### PR DESCRIPTION
**Pull request by laka3000**
#### What does this PR do?

changes Collapsible children visibility according to its state

#### Where should the reviewer start?

`src/js/components/Collapsible/Collapsible.js`

#### What testing has been done on this PR?

Storybook:

 - Collapsible (nested)
 - Accordion

#### How should this be manually tested?

Storybook:

 - Collapsible (nested)
 - Accordion

#### What are the relevant issues?

Fixes #4498

#### Screenshots (if appropriate)

Peek 2020-09-04 15-29

#### Is this change backwards compatible or is it a breaking change?

backwards compatible, expected changes to Collapsible snapshots

### CODE REVIEW

**Review by jcfilben — APPROVED** [review]
Nice job! Looked over PR and tested on storybook

**Review by ShimiSun — COMMENTED** [review]
Important fix, thank you for this PR.
We often don't use the `style.visibility` property to control accessibility behavior in grommet. so I'm wondering if in order to be more consistent with other components accessibility behavior we should use `tabIndex` or mimic the behaviors of Accordion, Layer or Drop, to make this functionality work. we'll need to dive into it before we can merge this PR.

**Comment by ericsoderberghp** [comment]
I think we should change Collapsible to work more like DropButton, where the children aren't rendered when the Collapsible isn't open or animating.

**Comment by ShimiSun** [comment]
I'll be closing this PR, but feel free to reopen or file a new PR that incorporates the feedback provided. Thanks!

**Pull request closed without merging**
