### PR TITLE
Support array of objects as border on borderStyle

### LINKED ISSUE #5699: TableCell does not support border props as an array in the way that Box does
Hello! Grommet's `Box` supports [passing in an array of border objects](https://github.com/grommet/grommet/blob/master/src/js/components/Box/StyledBox.js#L211-L217) to apply different styles to different sides of a Box. `TableCell` does not support the same functionality, and trying to pass in an array causes the border to be the default border on all sides. 

### Expected Behavior

Ideally in my opinion, `TableCell` should support passing in a border as an array; or, the [types for TableCell](https://github.com/grommet/grommet/blob/master/src/js/components/TableCell/index.d.ts#L28-L30) should be amended to not extend BoxProps's border style

### Actual Behavior

The TableCell and Box border styles don't have the same level of support

### URL, screen shot, or Codepen exhibiting the issue

The CodeSandbox below demonstrates how Boxes support border props as an array, and that TableCell does not

https://codesandbox.io/s/grommet-v2-template-forked-vxft5?file=/index.js

### Your Environment
- Grommet version: 2.17.3

### PR DESCRIPTION
**Pull request by leossantiago**
#### What does this PR do?

Allows TableCell to receive an array of objects as `border`, making it possible to use different sizes for each and every side of it. This is accomplished by making `borderStyle` method iterate through all entries of the array. The logic used by other components (Box and Grid) was also updated.

#### Where should the reviewer start?

`src/js/utils/border.js`

#### What testing has been done on this PR?

Manual testing and snapshot testing.

#### How should this be manually tested?

Same test case provided by the reporter:

```js
import React from 'react';

import { grommet, Box, Table, Grommet, TableHeader, TableCell } from 'grommet';

export const Default = () => (
  <Grommet theme={grommet}>
    <Box 
      margin="medium"
      border={[
        { side: "top", size: "medium" },
        { side: "right", size: "large", color: "brand" }
      ]}
    >
      boxes have robust border properties
    </Box>
    <Table pad="small">
      <TableHeader>
        <TableCell border={{ side: 'top', size: 'medium' }}>
          cell supports some of the same properties
        </TableCell>
        <TableCell
          border={[
            { side: 'right', size: 'medium' },
            { side: 'bottom', size: 'large' },
          ]}
        >
          but does not support border as an array
        </TableCell>
      </TableHeader>
    </Table>
  </Grommet>
);
```

#### What are the relevant issues?

Closes #5699 

#### Do the grommet docs need to be updated?

No.

#### Should this PR be mentioned in the release notes?

No.

#### Is this change backwards compatible or is it a breaking change?

Backwards compatible.

### CODE REVIEW

**Review by jcfilben — APPROVED** [review]
This looks good! Thanks for also including a jest test.

We will need to update the documentation for Table on the [grommet-site](https://github.com/grommet/grommet-site) repo.

**Review by taysea — APPROVED** [review]
Thanks for the enhancement!

**Review by amandadupell — APPROVED** [review]
lgtm!

**Comment by jcfilben** [comment]
Opened a PR for documentation here: https://github.com/grommet/grommet-site/pull/337

**Review by jcfilben — APPROVED** [review]

**Review by ericsoderberghp — APPROVED** [review]

**Pull request merged**
