### PR TITLE
Fix for #1374

### PR DESCRIPTION
**Pull request by Slumber86**
Changed class on creation and added at first user interaction

#### What does this PR do?
Solves the issue #1374

#### Where should the reviewer start?
See the issue

#### What testing has been done on this PR?
Automated testing updated and  manual testing

#### How should this be manually tested?
Yes, for autoplay

#### Do the grommet docs need to be updated?
No, it's just a fix

#### Should this PR be mentioned in the release notes?
It's just a fix

#### Is this change backwards compatible or is it a breaking change?
Backward compatible

### CODE REVIEW

**Comment by alansouzati** [comment]
hey @Slumber86 can you join our slack channel? I have few ideas for this that I would like to share with you. it will be easier to cat rather than describe the changes here.

http://slackin.grommet.io

**Comment by Slumber86** [comment]
@alansouzati I'm in, the only problem can be the timezone, I'm in Europe, You are in SF, right?

**Comment by Slumber86** [comment]
I've modified the PR to comply with your coding standards.

**Comment by alansouzati** [comment]
Thanks for your contribution. Welcome to the team!

**Comment by Slumber86** [comment]
You're welcome 👍

**Pull request merged**
