### PR TITLE
 Changed FormField to handle required with an initial value to fix issue #2948

### PR DESCRIPTION
**Pull request by ericsoderberghp**
#### What does this PR do?

 Changed FormField to handle required with an initial value to fix issue #2948

#### Where should the reviewer start?

FormField.js

#### What testing has been done on this PR?

storybook

#### How should this be manually tested?

storybook

#### What are the relevant issues?

#2948 

#### Do the grommet docs need to be updated?

done

#### Should this PR be mentioned in the release notes?

yes

#### Is this change backwards compatible or is it a breaking change?

backwards compatible

### CODE REVIEW

**Comment by oorestisime** [comment]
Should we add a test that verifies initial value handling? Like we add a a formfield with initial value we hit submit we make sure there is no required label?

**Comment by oorestisime** [comment]
@ericsoderberghp i added a test just to be on the safe side. i think it is good togo

**Comment by ShimiSun** [comment]
@oorestisime, I think we can merge this one, can you please resolve the conflict?

**Comment by ShimiSun** [comment]
I resolved the conflicts but noticed the following warnings, both of `yarn test` and storybook 
```
 PASS  src/js/components/Form/__tests__/Form-test.js
  ● Console

    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:102
      Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
      
      Check the render method of `Context.Consumer`.
          in FormField (created by Context.Consumer)
          in WithTheme(FormField) (created by FocusableComponent)
          in FocusableComponent (created by WithTheme(FormField))
          in WithTheme(FormField)
          in form (created by Form)
          in Form
          in div (created by Context.Consumer)
          in StyledComponent (created by StyledGrommet)
          in StyledGrommet (created by Grommet)
          in Grommet
    console.error node_modules/react-dom/cjs/react-dom.development.js:506
      Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
      
      Check the render method of `Context.Consumer`.
          in FormField (created by Context.Consumer)
          in WithTheme(FormField) (created by FocusableComponent)
          in FocusableComponent (created by WithTheme(FormField))
          in WithTheme(FormField)
          in form (created by Form)
          in Form
          in div (created by Context.Consumer)
          in StyledComponent (created by StyledGrommet)
          in StyledGrommet (created by Grommet)
          in Grommet

 PASS  src/js/components/FormField/__tests__/FormField-test.js
  ● Console

    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:102
      Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
      
      Check the render method of `Context.Consumer`.
          in FormField (created by Context.Consumer)
          in WithTheme(FormField) (created by FocusableComponent)
          in FocusableComponent (created by WithTheme(FormField))
          in WithTheme(FormField)
          in div (created by Context.Consumer)
          in StyledComponent (created by StyledGrommet)
          in StyledGrommet (created by Grommet)
          in Grommet
```

**Pull request merged**
