### PR TITLE
Add support for border for Grid similar to Box

### PR DESCRIPTION
**Pull request by srallen**
Signed-off-by: Sarah Allen <sarah@zooniverse.org>

#### What does this PR do?

Add support for border to Grid with similar function as Box. Toward #3654

#### Where should the reviewer start?
The updates to Grid.js and StyledGrid.js for border prop support.

#### What testing has been done on this PR?
Added to the Grid spec file snapshot tests for border. Updating the snapshots updated several unrelated snapshots; I'm not sure how to prevent that from happening.

#### How should this be manually tested?
A storybook story has been added for Grid with border.

#### Any background context you want to provide?
This is for #3654 to expand the styling configuration by prop for Grid. This does not close it as there may be others that are wanted, like pad support.

#### What are the relevant issues?
#3654 

#### Do the grommet docs need to be updated?
Yes, to note the support for border for Grid.

#### Should this PR be mentioned in the release notes?
Yes.

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible.

### CODE REVIEW

**Comment by srallen** [comment]
I'll have a look at that CI failure hopefully today or tomorrow. Tests passed when run locally after the snapshot updates.

**Comment by ericsoderberghp** [comment]
I'm good with the code changes. It looks like there are some snapshot issues though.

**Comment by srallen** [comment]
@ericsoderberghp this is ready for review again. I reverted the unrelated snapshots that had gotten updated and causing the CI failure. I'm presuming there's a way to run the jest CLI snapshot update for a single component, but I'm not very familiar with this as jest isn't used with the app I work on. Hope to at least get another PR in during hacktoberfest, so I'll have a look then. Thanks!

**Review by ericsoderberghp — APPROVED** [review]

**Comment by ericsoderberghp** [comment]
Thanks for your contribution!

**Pull request merged**
