### PR TITLE
Changed Box and TableCell to improve performance when changing theme background

### PR DESCRIPTION
**Pull request by ericsoderberghp**
#### What does this PR do?

Changed Box and TableCell to improve performance when changing theme background.
The essence of these changes are to use a memo for the updated theme value.

#### Where should the reviewer start?

Box.js

#### What testing has been done on this PR?

Used the code from the sandbox in the issue.

#### What are the relevant issues?

#5406 

#### Do the grommet docs need to be updated?

no

#### Should this PR be mentioned in the release notes?

yes

#### Is this change backwards compatible or is it a breaking change?

backwards compatible

### CODE REVIEW

**Comment by shc023** [comment]
Thanks for getting on this so quickly @ericsoderberghp ! Do you know what the release timeframe might look like once landed?

**Review by halocline — APPROVED** [review]

**Review by halocline — COMMENTED** [review]
The changes look good to me from a code standpoint. Looks like Jest in the is reporting snapshot changes. Need to investigate those.

**Comment by halocline** [comment]
> Thanks for getting on this so quickly @ericsoderberghp ! Do you know what the release timeframe might look like once landed?

@shc023 Once merged, this fix will be available immediately on [Grommet's stable branch](https://github.com/grommet/grommet#stable). I don't believe there is a date set (yet) for the next release, but think weeks not months.

**Comment by shc023** [comment]
> > Thanks for getting on this so quickly @ericsoderberghp ! Do you know what the release timeframe might look like once landed?
> 
> @shc023 Once merged, this fix will be available immediately on [Grommet's stable branch](https://github.com/grommet/grommet#stable). I don't believe there is a date set (yet) for the next release, but think weeks not months.

Thanks for the weeks ballpark, very helpful!

**Review by taysea — APPROVED** [review]

**Comment by MikeKingdom** [comment]
Looks great to me and thanks for fixing this!

**Comment by shc023** [comment]
Looks like release to stable is silently failing on CircleCI:

Screen Shot 2021-07-01 at 11 22 51 AM

**Comment by ericsoderberghp** [comment]
> @halocline @taysea @MikeKingdom @ericsoderberghp
> 
> Looks like release to stable is silently failing on CircleCI:
> 
> Screen Shot 2021-07-01 at 11 22 51 AM

Thanks for calling our attention to this!

**Pull request merged**
