### PR TITLE
Allow routed Anchor links to open in new tab via CMD + Click

### PR DESCRIPTION
**Pull request by leonardodino**
#### What does this PR do?
Prevent JS to interfere with shortcuts to open a link in a new tab.

#### Where should the reviewer start?
this [diff](https://github.com/grommet/grommet/pull/1370/commits/cb51da2770ba84a81bc0157249068fa9b38f4346) on `src/js/components/Anchor.js`. 

#### What testing has been done on this PR?
`pre-commit` hooks + local testing

#### How should this be manually tested?
Linking the project and cmd+clicking some links

#### Any background context you want to provide?
I think it's frustrating for SPA's to break this native behavior.

#### Do the grommet docs need to be updated?
No, it's just a fix.

#### Is this change backwards compatible or is it a breaking change?
backwards compatible.

### CODE REVIEW

**Comment by leonardodino** [comment]
I couldn't find a nice way to add unit tests without including **at least one of**:
1. a `react-router` mock
2. `enzime` *or another library that dispatches events on components.*

Thanks for your time. 😄
Grommet is an awesome project  👏

**Comment by alansouzati** [comment]
I love that. Thanks for adding this functionality. Bem vindo ao time Grommet 👍

**Comment by leonardodino** [comment]
Thanks for the quick answer :D @alansouzati 

Should I make this change to the `<Button>` component too? another PR?
As far as i can see *(a quick search)* these are the only components that use direct router navigation.

Valeu! :v:

**Comment by alansouzati** [comment]
Yeah that would be great if you can send another contribution for the Button. I'm happy to do it if you prefer, but my inclination is for you to do it since you had the idea in the first place.

**Comment by leonardodino** [comment]
I dont mind for commit counts. I bet the diff would be the same anyways. (:

Implementing (correctly) the idea is what matters most.
I guess you know that anyone that says otherwise is against what _open-source_ stands for.  😉 

For the sake of brevity, and faster turnaround, I opened #1373

**Pull request merged**
