### PR TITLE
MaskedInput scroll bars goes back to the top fix

### PR DESCRIPTION
**Pull request by IanKBovard**
#### What does this PR do?
Addresses issue #3854 where the scrollbar would move to the top on every mouse over. There is a useEffect hook in DropContainer.js that looks like, to me, just creates and cleans up events. That hook had a dependency array with dependencies passed through to it causing it to run on every update. I removed the dependencies from the array causing the hook to only run on mount, and unmount(which, i think, is what was intended).

#### What testing has been done on this PR?
Manual testing in storybook

#### How should this be manually tested?
Tested with storybook.

#### What are the relevant issues?
issue #3854 

#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
no
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Comment by IanKBovard** [comment]
One more thing, before the change to hooks DropContainer had componentDidUpdate with place(true). I don't see anywhere in this file that place ever gets called with true.

**Comment by ericsoderberghp** [comment]
All of those properties in the dependency array are there because the functions inside use them. So, if a caller changes any of them, the behavior should align with the changes. I'd be curious to know what prop was changing, causing the effect to be re-evaluated. I didn't see any obvious ones in the list but perhaps I'm missing something.

**Comment by IanKBovard** [comment]
Thanks for responding. I understand that, what I don't understand is when you need to remake the event handlers. Before the change to hooks, events were created onMount and removed on unMount. When refactoring to hooks isn't the intention to keep previous functionality?

compare : before hooks to now.
https://github.com/grommet/grommet/blob/f4611c750e297e560d35a6403f2eae41a20a4ad7/src/js/components/Drop/DropContainer.js

the only thing that changed onUpdate was this.place(true); which is not represented in the current code.

**Comment by ericsoderberghp** [comment]
Superseded by https://github.com/grommet/grommet/pull/4051

**Pull request closed without merging**
