### PR TITLE
Fix RadioButton extend

### LINKED ISSUE #4172: radioButton.extend applied to two DOM elements
### Expected Behavior

Theming should only apply to one or one type of DOM element.

### Actual Behavior

radioButton.extend is being applied to the box surrounding the indicator as well as the overall radiobutton wrapper. 

### URL, screen shot, or Codepen exhibiting the issue

Here, I've applied this to the theme:
```
radioButton: {
   extend: 'border: 1px solid red;',
},
```
Notice how two different things are being affected here:
Screen Shot 2020-06-10 at 11 24 15 AM

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: Stable
- Browser Name and version: Chrome 83.0.4103.97
- Operating System and version (desktop or mobile): Mac 10.14.6

### PR DESCRIPTION
**Pull request by jcfilben**
#### What does this PR do?
Fixes RadioButton so that when `radioButton.extend` is used in the theme it is not applied to two DOM elements

#### What testing has been done on this PR?
Testing with yarn storybook and yarn test

#### How should this be manually tested?
Add `RadioButton.extend: 'border: 1px solid red;'` to a theme and see that it is no longer being applied twice

#### What are the relevant issues?
Closes #4172 

#### Screenshots (if appropriate)
Before:
Screen Shot 2020-07-29 at 1 35 14 PM
After:
Screen Shot 2020-07-29 at 1 37 09 PM
After with container extend: 'border: 1px solid blue;'
Screen Shot 2020-08-07 at 10 47 26 AM

#### Do the grommet docs need to be updated?
Yes, updated in this PR

#### Should this PR be mentioned in the release notes?
Yes
Note: Previously `radioButton.extend` applied to the RadioButton and the container around the RadioButton. Now `radioButton.extend` only applies to the styling of the RadioButton and `radioButton.container.extend` applies to only the container.
To maintain any previous styling done with `radioButton.extend` add the styling to `radioButton.container.extend` as well.

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

**Comment by ShimiSun** [comment]
Added @taysea to review since she filed the issue.

**Comment by ShimiSun** [comment]
Thank you for this PR, it drove us to good discussions, here are some of the resolutions:
1. Removing the way to apply styles to the whole container wouldn't be backward compatible.
2. We should add a container option to RadioButton theme, that will apply the styles for the whole container and then remove the suggested style in this Pr.
3. here is the suggested structure of the theme:
```
    radioButton: {
      border: {
        color: {
          dark: 'rgba(255, 255, 255, 0.5)',
          light: 'rgba(0, 0, 0, 0.15)',
        },
        width: '2px',
      },
      checked: {
        radius: '100%',
        // background: {
        //  color: undefined,
        // },
        // color: { dark: undefined, light: undefined },
        // extend: undefined,
      },
      unchecked: {},
      // color: undefined,
      hover: {
        // background: {
        //   color: undefined,
        // },
        container: {},
        border: {
          color: {
            dark: 'white',
            light: 'black',
          },
        },
      },
      icon: {
        // size: undefined,
        // extend: undefined,
      },
      icons: {
        // circle: undefined,
      },
      gap: 'small',
      size: `${baseSpacing}px`,
      label: {
        font: {
          // weight: undefined,
        },
      },
      container: {
        // extend
      },
      // extend
    },
```

**Comment by ShimiSun** [comment]
I think the PR is missing the removal of the duplicated `extend` assignment. we should fix the bug and put a proper Release Not comment that communicates how the users that have been using `radioButton.extend` should deal with the impact of this change. Please add the note to the PR's release note section.

**Comment by jcfilben** [comment]
I am a little confused should I switch the PR back to the way it was before where the `${props => props.theme.radioButton.extend};` on line 36 was removed and there was no `radiobutton.container.extend`?

Or am I just adding a release note that explains the new behavior of `radiobutton.extend` and `radiobutton.container.extend`

**Comment by ShimiSun** [comment]
> I am a little confused should I switch the PR back to the way it was before where the `${props => props.theme.radioButton.extend};` on line 36 was removed and there was no `radiobutton.container.extend`?
> 
> Or am I just adding a comment about the release note that explains the new behavior of `radiobutton.extend` and `radiobutton.container.extend`

Both :)
We need to fix the bug and remove the duplication, and we also need to provide guidance for the users that are using `radiobutton.extend` and may experience side effects from this fix hence. we need the release notes comment.

**Comment by ShimiSun** [comment]
@taysea can you add a snippet how this change impacts the design system and the before and after code of its theme, it might be helpful for composing a useful note for the release notes.

**Comment by taysea** [comment]
> @taysea can you add a snippet on how this change impacts the design system and the before and after code of its theme? it might be helpful for composing a useful note for the release notes.

Yes I can do that!

**Comment by jcfilben** [comment]
Updated release note section

**Comment by taysea** [comment]
> Updated release note section

Nice, that looks good to me! Think this is good to merge

**Comment by ShimiSun** [comment]
@taysea thank you dear! This PR won't take place in the upcoming release, it will be merged afterward.

**Comment by ShimiSun** [comment]
@taysea since this PR will cause an issue with the design-system theme, can we please prep a PR on the theme side that addresses the changes of this PR? this way we can merge those two together and won't see problems with how the site is rendering.

**Comment by taysea** [comment]
@ShimiSun I've created the theme PR here: https://github.com/grommet/grommet-theme-hpe/pull/104

**Review by ShimiSun — APPROVED** [review]

**Pull request merged**
