### PR TITLE
Added fix for CSS variables support (#2363)

### PR DESCRIPTION
**Pull request by sofiageo**
#### What does this PR do?
Adds support for CSS variables color normalization.

#### What testing has been done on this PR?
Manual testing and automated testing

#### Any background context you want to provide?
This PR is mostly for discussion, as I'm not aware of the performance consequences it might have or any unwanted side effects.

#### What are the relevant issues?
#2363 2363

#### Do the grommet docs need to be updated?
I don't think so.

#### Is this change backwards compatible or is it a breaking change?
Should be backwards compatible

### CODE REVIEW

**Comment by ShimiSun** [comment]
Thanks for the PR buddy!

The Chroma tests found a broken snapshot on https://storybook.grommet.io/?path=/story/grommet--vars. 
It seems that the background color isn't applied anymore with your changes.
You can find your storybook changes on the PRs Netlify deployment (click on `Details)
https://deploy-preview-3417--sad-tereshkova-173d07.netlify.com/?path=/story/grommet--vars.

This is a screenshot from the broken snapshot (https://www.chromaticqa.com/build?appId=5d9774839a6eff00203f5cbf&number=38)
Screen Shot 2019-10-04 at 6 50 44 PM

**Comment by sofiageo** [comment]
Thanks @ShimiSun - I kinda rushed it a bit but the feedback was necessary. I have much better understanding now and I think I'm close to an implementation that work on all cases. I will make some more testing and see If and how and if I can change this PR or I need to make a new one.

**Comment by ShimiSun** [comment]
Hi buddy, any updates on this one?

**Comment by sofiageo** [comment]
> Hi buddy, any updates on this one?

Hi @ShimiSun - I've been extremely busy the past 1,5 week. I can start working on it tomorrow or Saturday.

**Comment by ShimiSun** [comment]
Sure thing. just wanted to make sure we are still on track with this PR, no rush.

**Comment by sofiageo** [comment]
Sorry for the extended delay. I've started at looking at the issue again so I will try to implement / test / close by the end of the week.

**Comment by sofiageo** [comment]
Unfortunately this is as far as I can take this. I think it gets a lot complicated and I'm not sure what the correct direction should be. 

Points that I'm not sure about at the moment:

1) Should CSS variables be defined on the global scope or on the StyledGrommet DOM.
2) Is this commit causing any performance issues
3) How should it work for SSR (I have no experience with SSR yet)
4) It looks like the snapshots are changed after this commit, should I commit the snapshots or it means I've broken something.
5) It doesn't look to be working with named colors e.g 'black' - For this reason I have to normalize the colors when the CSS variables are defined. I'm probably missing the function that translates that to r/g/b.

I will try to pick up some easier issues next time :) But any comments you have are welcome.

p.s I had to force push the branch in order to keep the same PR without the previous changes. I'm not sure if that is causing any issues.

**Comment by ShimiSun** [comment]
This PR has a long overdue, and we'll be closing it for now, feel free to reopen if still relevant.

**Pull request closed without merging**
