### PR TITLE
Add support of "height/width={{min:x, max:y}}" for Box.

### PR DESCRIPTION
**Pull request by jim-king-2000**
#### What does this PR do?
Add support of "height/width={{min:x, max:y}}" for Box.

#### How should this be manually tested?
See Box/MinMax.js in the storybook.

#### What are the relevant issues?
#3136 

#### Do the grommet docs need to be updated?
Yes.

#### Should this PR be mentioned in the release notes?
Yes.

#### Is this change backwards compatible or is it a breaking change?
It is backwards compatible.

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
This is looking good, just need to figure out what's up with the tests.

**Comment by ShimiSun** [comment]
Thank you @jim-king-2000 for your contribution! great work!

**Comment by jim-king-2000** [comment]
I'm looking forward to the release.

**Comment by ShimiSun** [comment]
@jim-king-2000 grommet 2.7.8 is out buddy! I just posted an announcement on our grommet-slack, Thank you!

**Comment by jim-king-2000** [comment]
Great! I'll integrate it into my project! Grommet is wonderful. Hope it could provide more and more components and become the best UI framework!

**Comment by jim-king-2000** [comment]
Hi @ShimiSun , just a kind remind, the document of Box should be updated. I see the storybook of Box has been updated.

**Comment by ShimiSun** [comment]
@jim-king-2000 Thanks for alerting buddy, Fixed 💜

**Pull request merged**
