### PR TITLE
implement same tag inheritance for gaps in box component

### LINKED ISSUE #3046: Should Box gap use the same tag as its parent Box?
### Expected Behavior

I would expect the gap elements within a `Box` component to have the same tag as the `Box` itself (e.g. `<Box as="span" gap="small">…</Box>` would also use `<span>` for each of the gaps).

### Actual Behavior

Instead, `Box` gaps are always `div` elements. This isn’t normally an issue, but since an `Anchor` with an icon uses an `"inline-flex"` `Box` component with a gap, it becomes an issue when that `Anchor` is within a `Paragraph`.

### Code Sandbox exhibiting the issue

Notice the console warnings when you first load this Code Sandbox: https://codesandbox.io/s/5yr109m8k4

### Steps to Reproduce

1. Create a `Paragraph`
2. Add an `Anchor` with an `icon` prop
3. Watch console for errors/warnings

### Your Environment

- Grommet version: 2.6.5
- Browser Name and version: Google Chrome 73.0.3683.103
- Operating System and version (desktop or mobile): MacOS Mojave 10.14.4

### Suggested Solution

Pass along the same `as`/`tag` props to the `StyledBoxGap` that are currently being passed to the `StyledBox` component.

### PR DESCRIPTION
**Pull request by buoyantair**
#### What does this PR do?
Attempts to fix #3046 
#### Where should the reviewer start?
Start with reviewing the Box component :)

#### What testing has been done on this PR?
Snapshot testing has been done for normal and nested use cases.
#### How should this be manually tested?
Maybe
#### What are the relevant issues?
#3046 
#### Do the grommet docs need to be updated?
Yes, this can effect workflows, the distinction needs to be documented
#### Should this PR be mentioned in the release notes?
Sure 😬 

#### Is this change backwards compatible or is it a breaking change?
Likely a breaking change.

### CODE REVIEW

**Comment by ShimiSun** [comment]
@ericsoderberghp I'd love your feedback on this potential breaking change.

**Comment by buoyantair** [comment]
Maybe I should write a proper test to make sure that the descendant Gap components of the Box component are actually always working via JSON structure or something instead of just snapshots?

**Comment by ShimiSun** [comment]
Tests are always a good idea :) Thanks!

**Comment by ericsoderberghp** [comment]
Snapshots should be enough. Just make sure the JSX is rich enough to cover the varieties of use.

**Comment by buoyantair** [comment]
@ShimiSun Heya, I have added some snapshot tests for this functionality, please do have a look!

**Comment by buoyantair** [comment]
I've updated the description to suit the same 😋 😊

**Comment by ericsoderberghp** [comment]
I don't think the proposed change is a good way to address the issue. A problem is that there are many DOM elements that are not valid nested, such as `<p />` and `<button />`. I'm contemplating two alternate approaches:
1) Enhance `gap` to take an object, for example: `gap={{ as: 'span', size: 'small' }}`. I think this represents a generally technically accurate approach.
2) Make Box smarter about the tag it uses for the gap component for specific cases. We could start by just saying that if the Box has `as="span"` than we will make the gap components use `span`. We could extend this as needed going forward. For instance, if the Box has `as="p"`, we would make the gap components use `span`.

**Comment by ShimiSun** [comment]
@buoyantair thank you for filing this PR and driving the discussion to the best approach of tackling issue #3046.
I like the two alternative solutions that @ericsoderberghp suggested, the only concern I have with the first suggestion of `gap={{ as: 'span', size: 'small' }}`, is whether the `as` property will need to be used elsewhere and not just for the `gap` property (it might be too futuristic to be concerned about it - but I couldn't help it)
I suggest closing this PR and put our resolutions on #3046. I do think we can reuse its testing for the future PR of solving the issue (thanks for adding tests - BTW)
Thoughts?

**Comment by buoyantair** [comment]
@ShimiSun Another concern I have with the first solution proposed by @ericsoderberghp is that, there is a set of rules to be followed when nesting elements within a parent element. This relation depends from one element to another. Like a `ul` element allows only an `li` element node(s) to be nested inside it.

There are 2 ways to solve this problem.

**Delegate the decision to the developer**: This is the simplest thing to do. We simply do not check for invalid nesting of elements. The user/developer is responsible for making sure their elements are nested semantically. 

**Maintain a map of all the html elements with which elements can be nested within them**: This is the more controlled approach where we use an error boundary to refer the user to the part of HTML spec which defines what elements are to be nested inside the given element... I have a feeling that we could use this functionality in pretty much every other component to make sure that the html content is always valid according to the html spec :D Obviously this is a little more complex... 😅

**Comment by ShimiSun** [comment]
I'm wondering if the simplest approach here will be to adjust the StyledBox to use the component pointed on the `as` tag. https://github.com/grommet/grommet/blob/90b1eee9272fc18a85d7e513018cc029f452c110/src/js/components/Box/StyledBox.js#L604

**Comment by MikeKingdom** [comment]
I think we should basically do two of the suggestions:
1) `gap={{ as: 'span', size: 'small' }}` - this gives the developer alot of control for interesting cases like `<Box as="ul" gap={{ as: 'li', size: 'small'}}`
2) If the gap-specific `as` isn't defined as above, default to the 'as' for the `<Box>`. This make most cases work with minimal or no change like the `<Anchor>` example in the issue, although this could be a breaking change. To avoid making it breaking you can just do the gap-specific solutiion we would have to fix cases like `<Anchor>` to pass the right thing in with the gap.

I don't really like trying to be smarter about choosing the gap 'as' automatically because in cases you didn't think of the developer has no solution.

I like simplicity when possible but allowing the developer full control to deal with other cases and avoid forcing them into a solution that doesn't use `<Box>`.
Thoughts?

**Comment by MikeKingdom** [comment]
This PR can be closed since it was instead addressed by #4464

**Comment by ShimiSun** [comment]
@MikeKingdom thank you for your work on this!!

**Pull request closed without merging**
