### PR TITLE
clairify RangeSelector docs for messages

### PR DESCRIPTION
**Pull request by sdowding**
#### What does this PR do?
Clarify the docs, before the wording was a bit choppy.

#### Where should the reviewer start?
Read the update.

#### What testing has been done on this PR?
Docs update...

#### How should this be manually tested?
?

#### Do the grommet docs need to be updated?
This is an update to the documentation

#### Should this PR be mentioned in the release notes?
No

#### Is this change backwards compatible or is it a breaking change?
just docs, backwards compatible

### CODE REVIEW

**Comment by ShimiSun** [comment]
Hi @sdowding can you run `yarn test update` and commit+push the updated snapshots to fix the build?

**Comment by sdowding** [comment]
@ShimiSun this makes it more clear, no? whats the disadvantage?

**Comment by taysea** [comment]
This sounds good to me! @ShimiSun @sdowding

**Comment by ShimiSun** [comment]
Thank you for your contribution

**Pull request merged**
