### PR TITLE
Added to title in tab to be able to accept a react node with TS

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
Fixes typescript issues
#### Where should the reviewer start?
/Tab/index.d.ts
#### What testing has been done on this PR?
I branched out grommet with these fixes and created a react app with passing in 
 <Tab title={<Text>Foo</Text>}><Text>Foo</Text></Tab>
to test for the error
#### What are the relevant issues?
#3193 
#### Do the grommet docs need to be updated?
done
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Comment by ShimiSun** [comment]
I'm curious to understand if we still need to use the `React.ReactNode`.

**Comment by oorestisime** [comment]
> I'm curious to understand if we still need to use the `React.ReactNode`.

https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/README.md#useful-react-prop-type-examples

in my understanding from the cheatsheet is that we probably only need ReactNode

**Comment by britt6612** [comment]
> > I'm curious to understand if we still need to use the `React.ReactNode`.
> 
> https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/README.md#useful-react-prop-type-examples
> 
> in my understanding from the cheatsheet is that we probably only need ReactNode

In the docs that I found the JSX.element is just returning essentially a react.element but the react.node should cover all of this so Ill do some more digging into why this element is still throwing an error even though we had react.node

**Comment by ShimiSun** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title
A collision of the Html `title` with Tab `title` prop.

**Pull request closed without merging**
