### PR TITLE
SelectMultiple - Improve alignment of open/close icon

### PR DESCRIPTION
**Pull request by jcfilben**
#### What does this PR do?
Fixes an issue in the `showSelectedInline` version of SelectMultiple the open/close arrow isn't in the same location when the drop is open vs closed.

Current behavior:

https://user-images.githubusercontent.com/54560994/190019309-0e101e74-5078-48d2-af34-2a9e0052e5bf.mp4

Fixed behavior:

https://user-images.githubusercontent.com/54560994/190019436-3faae639-ea79-42e3-859b-15cdb872a6a2.mp4

Note: this PR also fixes an issue where the summary selection content was getting vertically squished when the screen has limited vertical space.

current:
Screen Shot 2022-09-13 at 4 21 48 PM

fixed:
Screen Shot 2022-09-13 at 4 21 26 PM

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### Do the grommet docs need to be updated?
No
#### Should this PR be mentioned in the release notes?
No, SelectMultiple component has not been released yet
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
I'm still seeing alignment issues:

https://user-images.githubusercontent.com/11637956/190028274-121cd33e-b59c-4099-86c6-14339b8c274d.mov

**Comment by jcfilben** [comment]
> I'm still seeing alignment issues

I adjusted the click target of the button to be larger, so this issue should be fixed now

**Review by britt6612 — APPROVED** [review]

**Review by ericsoderberghp — APPROVED** [review]

**Comment by ericsoderberghp** [comment]
This is definitely an improvement. So, I'm happy to merge this as such.

However, I think we still have a visual alignment issue. With the hpe theme, the visual placement of the down caret when closed doesn't align with the visual placement of the up caret when open. The caret when open is noticeably lower on the page than the caret when closed.

Screen Shot 2022-09-15 at 9 42 01 AM

Screen Shot 2022-09-15 at 9 42 11 AM

**Comment by jcfilben** [comment]
> However, I think we still have a visual alignment issue. With the hpe theme, the visual placement of the down caret when closed doesn't align with the visual placement of the up caret when open. The caret when open is noticeably lower on the page than the caret when closed.

I adjusted the alignment in this new pull request: https://github.com/grommet/grommet/pull/6335

**Pull request merged**
