### PR TITLE
Dependency upgrades and cleanups

### PR DESCRIPTION
**Pull request by jcfilben**
#### What does this PR do?
Builds off of https://github.com/grommet/grommet/pull/7286, just upgrades a few more dependencies and cleans up some outdated dependencies.

Freezes styled components version, this will be upgraded seperatly because it is causing snapshot changes

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
no
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Review by britt6612 — APPROVED** [review]
LGTM!

**Comment by britt6612** [comment]
Im getting the following:

● DateInput › format with date bounds

    thrown: "Warning: An update to %s inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act%s"

      at _getError (node_modules/jest-circus/build/utils.js:432:18)
          at Array.map (<anonymous>)

  ● DateInput › format with date bounds

    Uncaught 'Warning: An update to %s inside a test was not wrapped in act(...).\n' +
      '\n' +
      'When testing, code that causes React state updates should be wrapped into act(...):\n' +
      '\n' +
      'act(() => {\n' +
      '  /* fire events that update state */\n' +
      '});\n' +
      '/* assert on the output */\n' +
      '\n' +
      "This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act%s"

**Comment by jcfilben** [comment]
@britt6612 I can't reproduce the act warning, could you test to see which dependency this is tied to?

**Review by taysea — APPROVED** [review]
Looks good for me on node 18 & 20.

**Review by britt6612 — APPROVED** [review]

**Pull request merged**
