### PR TITLE
TypeScript Box border - Adding reusable types

### PR DESCRIPTION
**Pull request by ShimiSun**
This PR is a follow up of a comment made by @oorestisime on @shabtaisharon PR. 
https://github.com/grommet/grommet/pull/3362
https://github.com/grommet/grommet/pull/3362/files#r326857694

### CODE REVIEW

**Comment by taysea** [comment]
I tested this in a local project with typescript. It rendered as expected and didn't flag anything in the code editor, but I got this warning in my console: "Warning: Failed prop type: Invalid prop `border` supplied to `Box`." The code I used was:
```
<Box 
border={[{color: "red", side: "top"}, {color: "blue", side: "bottom"}]}
height="small"
width="small"
/>
```

**Comment by ShimiSun** [comment]
@taysea thanks for your review 💟 
I'm thinking your typescript project may not be using the grommet master branch since this feature is a recent addition (from this morning) and that may be a reason for the warning you are seeing.
Just to double-check, I tried to reproduce the warning on storybook (master branch), with the same border values you were using 👆 and wasn't able to see the warning you referred too.
Screen Shot 2019-09-30 at 1 02 39 PM

**Comment by taysea** [comment]
That must have been it @ShimiSun. Thanks for testing in storybook.

**Comment by martinRoss** [comment]
Is this something that's possible for list itemProp borders? I'm trying to set the left border of the active list item and it seems that the border prop doesn't accept an array here. 

```
itemProps={
  selected >= 0 ? { [selected]: {
    background: "light-3",
    border: [{side: 'all', color: 'light-5' }, { side: 'left', color: 'brand'}]
  }} : undefined
}
```

**Pull request merged**
