### PR TITLE
Add announce to DataChart Detail for series label or property and value

### PR DESCRIPTION
**Pull request by mcbouslog**
#### What does this PR do?
- adds `AnnounceContext` and `announce` to DataChart Detail to announce Detail content with screen reader

#### Where should the reviewer start?
- review issue #7309 

#### What testing has been done on this PR?
- I'm having difficulties creating test(s), suggestions welcome!

#### How should this be manually tested?
- locally, review http://localhost:9001/?path=/story/visualizations-datachart-detail--detail with screen reader, noting announcement of Detail content as arrow or mouseover series values

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

#### Any background context you want to provide?
- I'm not sure if the related issue is valid or if this is the best solution, ok to close if not

#### What are the relevant issues?
- issue #7309 

#### Do the grommet docs need to be updated?
- I don't think so

### CODE REVIEW

**Comment by jcfilben** [comment]
Hi @mcbouslog thanks for working on this! I saw that this PR is marked as a draft, I just wanted to check if you wanted a review on this or if you were still making adjustments and we should hold off on reviewing

**Comment by mcbouslog** [comment]
> Hi @mcbouslog thanks for working on this! I saw that this PR is marked as a draft, I just wanted to check if you wanted a review on this or if you were still making adjustments and we should hold off on reviewing

I'm done making changes to `Detail.js`, but marked it as draft for the lack of test(s). I'll change it to ready for review for feedback; thank you!

I'm not sure about the linked issue and if this is the best solution, open to suggestion (including simply this isn't an approach the Grommet team would like to go with).

**Review by jcfilben — APPROVED** [review]
Looks good!
I tested with voiceover on chrome. I wasn't able to navigate with arrow-keys when I had voiceover running, but I did get the screenreader announcements of the details when I moused over them. I think the keyboard behavior with voiceover can be handled in a separate issue, this PR is a nice step in the right direction for DataChart's accessibility behavior.

No worries about not having a test for this, screenreader behavior is difficult to make automated tests for.

**Review by halocline — APPROVED** [review]
Thank you for your contribution, @mcbouslog!

**Comment by jcfilben** [comment]
Linking to a separate issue for the keyboard behavior in voice over: https://github.com/grommet/grommet/issues/7319

**Comment by eatyourgreens** [comment]
>I wasn't able to navigate with arrow-keys when I had voiceover running, but I did get the screenreader announcements of the details when I moused over them. 

Sorrty, I've been pointed towards this issue by a comment on https://github.com/zooniverse/front-end-monorepo/issues/6322, but I think I'm missing a lot of context.

I just wanted to say that screen reader users, by definition, can't use a mouse. So any fix for this issue must involve making the individual bars available to keyboard navigation, whether that's tab navigation or the browsing keys for a particular screen reader (eg. VO-Right Arrow in Safari/VoiceOver.)

**Comment by jcfilben** [comment]
> I just wanted to say that screen reader users, by definition, can't use a mouse. So any fix for this issue must involve making the individual bars available to keyboard navigation, whether that's tab navigation or the browsing keys for a particular screen reader (eg. VO-Right Arrow in Safari/VoiceOver.)

Hey, @eatyourgreens this PR is just one part of the solution, I think the keyboard behavior can be handled in a separate PR. I realize that the DataChart accessibility isn't complete without both of these parts working correctly but I wanted to get this PR in to at least fix the announcements and not block merging this because of the keyboard behavior.

**Pull request merged**
