### PR TITLE
Fix range selector step issue

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?
Fixes issue with step on range selector with mouse interaction.

#### Where should the reviewer start?
src/js/components/RangeSelector/RangeSelector.js

#### What testing has been done on this PR?
The issue noted in Issue #3360 was recreated in a local project. Then after the fix, the changes were tested in a storybook example and the example provided in order to confirm successful changes.

#### How should this be manually tested?
Create a RangeSelector with a step value and ensure that as the mouse moves either end of the range selector that the value is adhering to the defined step.

#### Any background context you want to provide?
The RangeSelector was creating a glitchy effect when a step was provided. For example, if the step was 3, the RangeSelector output value would jump from 0 -> 2 -> 4 -> 3 -> 5 -> 7 -> 6 and so on. This does not achieve the intended goal of only allowing the RangeSelector to reach values in increments of 3.

#### What are the relevant issues?
Issue #3360 

#### Do the grommet docs need to be updated?
No.

#### Should this PR be mentioned in the release notes?
No.

#### Is this change backwards compatible or is it a breaking change?
Yes, this is backwards compatible.

### CODE REVIEW

**Comment by ShimiSun** [comment]
I'd like to get some information on why the new formula is working, and where the previous one was failing.

**Comment by taysea** [comment]
The existing calculation would create the following (where x is the value of the mouse location and y is the value of the range selector):
```
x | y
0 | 0
1 | 2
2 | 4
3 | 3
4 | 5
...
```
Because of this, you can see how the output does not create the expected step output and instead creates a glitchy output. What we expect to see is:
```
x | y
0 | 0
1 | 3
2 | 3
3 | 3
4 | 6
5 | 6
6 | 6
...
```
The updated calculation achieves that.

**Comment by ShimiSun** [comment]
@taysea Thank you for working on this PR! 
I'm ok with merging it, but I'm concerned about two things:
1. How come our tests didn't catch it? (all snapshots haven't changed)
2. I need a more asserted confirmation then just a review to confirm this fixed behavior.

Would you be willing to add tests on src/js/components/RangeSelector/__tests__/RangeSelector-test.js with a couple of tricky uses cases that this PR is solving?

**Comment by taysea** [comment]
Yes, @ShimiSun I can do that. It does seem strange that the existing was passing the tests.

**Comment by taysea** [comment]
I looked into the existing test, and this is how the step is being tested:
```
  test('step', () => {
    const component = renderer.create(
      <Grommet>
        <RangeSelector step={10} values={[20, 30]} />
      </Grommet>,
    );
    const tree = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
```
It doesn't seem to be testing how the position of the range selector shifts when the mouse drags an edge. That must be why the current version is passing the test. I'll work on creating a new test and confirm that the existing version fails but my change passes.

**Comment by taysea** [comment]
Verified with Chromatic: https://www.chromaticqa.com/build?appId=5d7a63beda813e00202faf9d&number=39

**Comment by ShimiSun** [comment]
Great! thank you @taysea !! 🎉

**Pull request merged**
