### PR TITLE
fix: Storybook - RangeInput/Bounds example

### PR DESCRIPTION
**Pull request by abdulbasithqb**
#### What does this PR do?
fix: Storybook - RangeInput/Bounds example

#### Where should the reviewer start?
Storybook - RangeInput/Bounds example

#### What testing has been done on this PR?
Manually clicking the + and - to ensure the expected behavior.

#### How should this be manually tested?
go to Storybook - RangeInput/Bounds example then click  + and - and validate it

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
fixes: #7242

#### Screenshots (if appropriate)

https://github.com/grommet/grommet/assets/134603758/21d4e066-e40c-43fa-a9b2-802e90eb4b46

#### Is this change backwards compatible or is it a breaking change?
No

### CODE REVIEW

**Review by jcfilben — COMMENTED** [review]
Thanks for working on this!

One small comment, as soon as the value hits the min or max the button should become disabled. In this PR the button only becomes disabled when we hit the min/max and then try to click the button again.

One potential solution is instead of the `setIsSubtractDisabled(true)` or `setIsAddDisabled(true)` being called in the onClick you could use a `useEffect` that gets called when the value changes and then check if the value is equal to the max/min and if it is set the button to be disabled.

**Comment by abdulbasithqb** [comment]
> Thanks for working on this!
> 
> One small comment, as soon as the value hits the min or max the button should become disabled. In this PR the button only becomes disabled when we hit the min/max and then try to click the button again.
> 
> One potential solution is instead of the `setIsSubtractDisabled(true)` or `setIsAddDisabled(true)` being called in the onClick you could use a `useEffect` that gets called when the value changes and then check if the value is equal to the max/min and if it is set the button to be disabled.

Done, please check

**Comment by abdulbasithqb** [comment]
> [ ](/abdulbasithqb)
> ` [fix: lint fix](/grommet/grommet/pull/7244/commits/c6f14e8214ddf3263948a4de0783bcb174f50bd2)`
Fixed

**Review by jcfilben — APPROVED** [review]

**Review by halocline — APPROVED** [review]
@abdulbasithqb, thank you for your contribution!

**Pull request merged**
