### PR TITLE
NEW NameValueList Component Box approach

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
Provides a first pass proposal and prototype examples for <NameValueList />.

`NameValueList` is essentially the parent `box` for `NameValuePair` 
`NameValuePair` was created in a separate file to keep code clean.

`NameValuePair` contains `Boxs` that are determining the direction for the `name text` and `value text`

To keep things simple on the users part I added a `layout` prop that can be leveraged to make up the different variants of `NameValueList`

## First Approach

After exploring this approach I found that it may be useful to have a `grid` layout. This would keep things more consistent. I wanted to get this out there though to start the conversation. 

**NameValueList API** 

```

export interface NameValueListProps {
  a11yTitle?: string,
  data?: array,
  layout?: string,
  pairProps?: boxProps,
  nameProps?: textProps,
  listProps?: boxProps,
  valueProps?: textProps,
  align?: object 

```

TODOs:

- Gather feedback
- Documentation
- Unit tests
- Stories
- mobile view (responsiveness)
- accessibility 
- grid layout (@taysea ) is going to be pushing this porition up here soon! 

#### Where should the reviewer start?
NameValueList.js
#### What testing has been done on this PR?
storybook
#### How should this be manually tested?
storybook
#### Any background context you want to provide?
[Figma file](https://www.figma.com/file/Ny7rYK5gI5VO4PtZsq6vGC/HPE-Name-Value-Pair?node-id=148%3A1936)
#### What are the relevant issues?
issue #5604 
Closes https://github.com/grommet/hpe-design-system/issues/1904

#### Do the grommet docs need to be updated?
eventually
#### Should this PR be mentioned in the release notes?
yes minor release
#### Is this change backwards compatible or is it a breaking change?
backwards compatibl

### CODE REVIEW

**Comment by halocline** [comment]
@britt6612 would it be possible to provide an updated definition of the prop types and their possible values? That'd be helpful to familiarize myself with the interface.

e.g.

```
export interface NameValueListProps {
  a11yTitle?: string,
  data?: array,   // would expect this to be an array of objects containing either 'key' and 'value' or 'name' and 'value'
  layout?: string, // what values are accepted here?
  pairProps?: boxProps, // adding a comment description of this prop would be helpful
  nameProps?: textProps, // adding a comment description of this prop would be helpful
  listProps?: boxProps, // adding a comment description of this prop would be helpful
  valueProps?: textProps, // adding a comment description of this prop would be helpful
  align?: object // what is this aligning?

```

I see some of this exists in the Story and will check out those examples more.

**Comment by halocline** [comment]
Wondering about `layout` vs. `direction`... 

Wondering about decoupling list direction and pair direction...  would decoupling provide the caller more flexibility by being able to have one prop controlling the list's direction (row or column) and another to control the pair's direction (row or column)? This would align closer with existing Grommet Box terminology as well as allow for 4 "layout" combinations instead of the current 3 (e.g. vertical, horizontal, stacked).

**Comment by britt6612** [comment]
> @britt6612 would it be possible to provide an updated definition of the prop types and their possible values? That'd be helpful to familiarize myself with the interface.
> 
> e.g.
> 
> ```
> export interface NameValueListProps {
>   a11yTitle?: string,
>   data?: array,   // would expect this to be an array of objects containing either 'key' and 'value' or 'name' and 'value'
>   layout?: string, // what values are accepted here?
>   pairProps?: boxProps, // adding a comment description of this prop would be helpful
>   nameProps?: textProps, // adding a comment description of this prop would be helpful
>   listProps?: boxProps, // adding a comment description of this prop would be helpful
>   valueProps?: textProps, // adding a comment description of this prop would be helpful
>   align?: object // what is this aligning?
> ```
> 
> I see some of this exists in the Story and will check out those examples more.

yes doing now!

**Comment by britt6612** [comment]
> Wondering about `layout` vs. `direction`...
> 
> Wondering about decoupling list direction and pair direction... would decoupling provide the caller more flexibility by being able to have one prop controlling the list's direction (row or column) and another to control the pair's direction (row or column)? This would align closer with existing Grommet Box terminology as well as allow for 4 "layout" combinations instead of the current 3 (e.g. vertical, horizontal, stacked).
> 
> Or do I specify these in the `listProps.direction` and `pairProps.direction` if I want that control?

So I added the `layout` with more of the Design-System in mind so that way other teams would be able to easier pass in which layout they would like and it would take care of everything for them however with keeping the community in mind I added the `{...listProps}` and the `{...pairProps}` that way they can override the direction and have which ever layout they desire.

**Comment by halocline** [comment]
RE: alignment - would be good to see the definitions for possible values.

Can I have a 'end' aligned 'name'? In the 'stacked' scenario, can I align centered? Should I be able to?

Wondering about the tradeoffs between distinct `align` vs. `pairProps.align` since `pairProps` is defined as `boxProps`?
Same question for the tradeoffs between distinct `layout` vs. `listProps.direction` since `listProps` is defined as `boxProps`?

Part of me likes the convenience of having `layout` or `direction` at the top-level API for convenience, but also like the minimal surface approach as well. In the current implementation, if I were to specify:
```
  <NameValueList data={data} layout="horizontal" listProps={{ direction: 'column' }} />
```
which would win?

**Comment by britt6612** [comment]
> RE: alignment - would be good to see the definitions for possible values.
> 
> Can I have a 'end' aligned 'name'? In the 'stacked' scenario, can I align centered? Should I be able to?
> 
> Wondering about the tradeoffs between distinct `align` vs. `pairProps.align` since `pairProps` is defined as `boxProps`?
> Same question for the tradeoffs between distinct `layout` vs. `listProps.direction` since `listProps` is defined as `boxProps`?
> 
> Part of me likes the convenience of having `layout` or `direction` at the top-level API for convenience, but also like the minimal surface approach as well. In the current implementation, if I were to specify:
> 
> ```
>   <NameValueList data={data} layout="horizontal" listProps={{ direction: 'column' }} />
> ```
> 
> which would win?

Im going to add some more examples for the `align` and how that would look those are great points that you brought up..

So something like this 

```

<NameValueList data={data} layout="horizontal" listProps={{ direction: 'column' }} />

```

The `listProps={{ direction: 'column' }} ` would win in this case which allows the user to create which every layout they wanted to but also keeping the 3 layouts of 'vertical', 'stacked' and 'horizontal' easy to achieve with just passing one prop as opposed to passing `listProps={{ direction: 'column' }} ` and `pairProps={{direction: 'column'}}` to achieve a `stacked` look

**Comment by britt6612** [comment]
> RE: Can I have a 'end' aligned 'name'? In the 'stacked' scenario, can I align centered? Should I be able to?

This is actually a good point I have a set `width` for the `name` so you would not be able to align I think this is something I ran into that's why we brought up the idea of having a grid but then maybe having a prop that controls the width of the name so users can control that aspect of it.

**Comment by britt6612** [comment]
Going to close this PR in favor of the Grid approach. We decided that was better for taking care of the responsiveness.

**Pull request closed without merging**
