### PR TITLE
Add tip as value for truncate on Text

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?

When truncate="tip", if the text has been truncated, the entirety of the text will be placed in a Tip.

#### Where should the reviewer start?
src/js/components/Text/Text.js

#### What testing has been done on this PR?
Adjusted Tip.js story to demo `truncate="tip"`.

#### How should this be manually tested?
Checkout deploy Tip.js under Text stories.

#### Any background context you want to provide?
Minimize implementation effort to be able to place truncated content into a tip.

#### What are the relevant issues?
Related to: https://github.com/grommet/hpe-design-system/issues/1503
Related to: https://github.com/grommet/hpe-design-system/pull/1734

#### Do the grommet docs need to be updated?
Updated here.

#### Should this PR be mentioned in the release notes?
Yes. Added `truncate="tip"` to Text.

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible.

### CODE REVIEW

**Review by ericsoderberghp — APPROVED** [review]

**Comment by ericsoderberghp** [comment]
Need to look into why the Button:Badge chromatic test is failing. I've run it twice and it fails in the same place.

**Comment by MikeKingdom** [comment]
> Need to look into why the Button:Badge chromatic test is failing. I've run it twice and it fails in the same place.

Seems like it has something to do with how the ref if being passed around. Badge seems like it's miscalculating contentRef width

**Comment by ericsoderberghp** [comment]
> > Need to look into why the Button:Badge chromatic test is failing. I've run it twice and it fails in the same place.
> 
> Seems like it has something to do with how the ref if being passed around. Badge seems like it's miscalculating contentRef width

I think it's because the Chromatic snapshot is being taken before the `useLayoutEffect` is running the initial `onResize` to stretch the badge if needed. Is there a way to delay the snapshot?

**Comment by ericsoderberghp** [comment]
Might want to try something like:
```
Badge.parameters = {
  chromatic: { delay: 50 }, // 50 is empirical
};
```

**Comment by MikeKingdom** [comment]
> Might want to try something like:
> 
> ```
> Badge.parameters = {
>   chromatic: { delay: 50 }, // 50 is empirical
> };
> ```

I can still make it happen locally. There are cases where nothing causes another render and no amount of waiting will help since nothing is coming.

Basically, useForwardedRef sets the .current of the passed in ref (in this case Badge's copy) in a useEffect which is called after Badge's useLayoutEffect. If nothing causes Text to get re-rendered then Badge won't ever see the real .current.

Making Badge use useEffect there instead does work, but that basically just points out the way useForwardedRef no works in Text is not backward compatible with anyone else passing a ref to Text.

**Comment by MikeKingdom** [comment]
Replaced by PR #5462

**Pull request closed without merging**
