### PR TITLE
Change zIndex for RangeSelector/EdgeControl

### PR DESCRIPTION
**Pull request by LeComptoirDesPharmacies**
#### What does this PR do?

It add the capacity to customize z-index of RangeSelector EdgeControl

#### How should this be manually tested?

Change the value in the theme and appreciate it on the DOM

#### What are the relevant issues?

This one => https://github.com/grommet/grommet/issues/5565

#### Do the grommet docs need to be updated?

Yes to say that its possible via theme on the component documentation

#### Should this PR be mentioned in the release notes?

As you want :) 

#### Is this change backwards compatible or is it a breaking change?

Fully compatible

### CODE REVIEW

**Comment by britt6612** [comment]
> I'v tried to update the jest snapshop using `npm run test-update` to make the **ci/circleci: jest** succeed. I got errors coming from code i haven't modified.

I added the updated snapshot!

**Comment by LeComptoirDesPharmacies** [comment]
Of course @britt6612, its here => https://github.com/grommet/grommet-site/pull/305

Thank you for your quick answer :)

**Comment by ericsoderberghp** [comment]
Just need to update the test snapshots now. `git pull` to pick up the merge with master. `yarn test-update` to update the snapshots.

**Comment by ericsoderberghp** [comment]
I think this needs some manual merging, to address the merge conflict files.

**Comment by britt6612** [comment]
> I think this needs some manual merging, to address the merge conflict files.

I can fix these conflicts I already have the branch locally!

**Review by jcfilben — COMMENTED** [review]
Changes look good. I think we should update the description and title of the PR to reflect the new direction the pr took after it was originally filed.

**Review by ericsoderberghp — APPROVED** [review]

**Comment by ericsoderberghp** [comment]
Thanks for the contribution!

**Pull request merged**
