### PR TITLE
Toast prevent interaction with elements after disappearing fix

### PR DESCRIPTION
**Pull request by Thuranel**
#### What does this PR do?
Fix issue #1572 

#### What testing has been done on this PR?
None

#### How should this be manually tested?
Create a Toast component hiding Buttons or other interactable elements. When the Toast completely disappear, check to see if you can interact with the Button.

#### What are the relevant issues?
#1572 

#### Do the grommet docs need to be updated?
No

#### Is this change backwards compatible or is it a breaking change?
backwards compatible

Special thanks to @j0nas for the help :)

### CODE REVIEW

**Comment by pho3nixf1re** [comment]
This seems to be a pretty important bug fix. What is the status here?

**Comment by alansouzati** [comment]
Sorry. I completely missed this. Let me review this.

**Comment by alansouzati** [comment]
Hey @Thuranel thank you so much for your contribution and again sorry for taking such a long time to get back to you on this.

I believe there is an easier way to solve this problem. What if we always send the `onClose` to `ToastContents` ? Here is a screenshot of the change that I did and it seems to work.

screen shot 2017-09-06 at 1 30 25 pm

Would you mind updating this Pull Request to reflect this?

**Comment by Thuranel** [comment]
Oh yea that seems way more simple. Going to update it tomorrow. Thanks for the input.

**Pull request merged**
