### PR TITLE
Next ts

### PR DESCRIPTION
**Pull request by RyanCCollins**
This PR adds typescript definitions to grommet NEXT.

Please hold off on reviewing / merging as I get this updated.

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
Would it be possible to generate the typescript files programmatically, based on the react-desc doc.js file content, similar to how the per-component README files are generated?

**Comment by RyanCCollins** [comment]
@ericsoderberg It’s certainly possible to do that yeah. I have an open issue to look into that. Will Post a link.

**Comment by abner** [comment]
Hi @RyanCCollins. Is this Typescript initiative still in course? If not, what would be the approach to use grommet components with Typescript? Thanks in advance

**Comment by RyanCCollins** [comment]
@abner We'd still love it to get grommet 2.0 statically typed.  I'm working on updating the codebase to latest and also want to look into automating the process of creating type annotations.  Unfortunately, I don't have much time to devote to the effort at the moment.  If you can help, it'd be very much appreciated!

**Pull request closed without merging**
