### PR TITLE
Fix axe issues for ArrayOfFormFields

### PR DESCRIPTION
**Pull request by ShimiSun**
#### What does this PR do?
Fixes accessibility issues in storybook for ArrayOfFormFields
#### Where should the reviewer start?
storybook file
#### What testing has been done on this PR?
local
#### How should this be manually tested?
strorybook
#### Do Jest tests follow these best practices?
N/A
#### Any background context you want to provide?
nope
#### What are the relevant issues?
#4068 #6124 
#### Screenshots (if appropriate)
Before
image (1)

After
image

#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
no
#### Is this change backwards compatible or is it a breaking change?
b-c

### CODE REVIEW

**Review by jcfilben — APPROVED** [review]
Looks good!

**Comment by ericsoderberghp** [comment]
Should we be automatically setting `aria-label` to the `label` property if no `aria-label` is provided?

**Comment by britt6612** [comment]
> Should we be automatically setting `aria-label` to the `label` property if no `aria-label` is provided?

good point we could or maybe a console warning for it? Im open to discussing either

**Comment by ShimiSun** [comment]
> Should we be automatically setting `aria-label` to the `label` property if no `aria-label` is provided?

Good comment. Yea, we can optimize FormField to set `aria-label` value from `label`, but we would need to ensure backward compatibility in case `aria` is provided.

**Review by ericsoderberghp — APPROVED** [review]

**Pull request merged**
