### PR TITLE
Storybook 7 upgrade

### PR DESCRIPTION
**Pull request by jcfilben**
#### What does this PR do?
Upgrades to use the latest storybook version

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
https://github.com/grommet/hpe-design-system/issues/3252
Closes https://github.com/grommet/grommet/issues/6228

#### Do the grommet docs need to be updated?
no
#### Should this PR be mentioned in the release notes?
no
#### Is this change backwards compatible or is it a breaking change?
backwards compatible

### CODE REVIEW

**Comment by jcfilben** [comment]
Marking as a draft while I look into the chromatic changes

**Comment by jcfilben** [comment]
> Marking as a draft while I look into the chromatic changes
Should be fixed now. I just had to update where storybook was grabbing the arguments we are passing to the grommet wrapper

**Review by taysea — APPROVED** [review]

**Review by halocline — COMMENTED** [review]
This is looking good, however I am noticing a couple things:

1) When retrieving the root index (e.g. `https://[domain]/`) I land on the first story under Accordion. Do we want the to resolve to "All"?
2) When running `build-storybook` I am receiving a handful of warnings in my terminal. They seem related to other storybook dependencies, but am curious if you had run into / investigated these warnings?

**Comment by jcfilben** [comment]
> 

> This is looking good, however I am noticing a couple things:
> 
> 1. When retrieving the root index (e.g. `https://[domain]/`) I land on the first story under Accordion. Do we want the to resolve to "All"?
> 2. When running `build-storybook` I am receiving a handful of warnings in my terminal. They seem related to other storybook dependencies, but am curious if you had run into / investigated these warnings?

1. This should be fixed now, 'All' should be the story we land on.
2. I did run into these warnings. Storybook 7 dropped support for webpack 4, I think these warnings are coming from storybook dependencies and addons that still have some cleanup to do from moving to webpack 5. I didn't see anything that looked too concerning in the warnings, but if we want we can always wait a little longer to upgrade and give more time for storybook 7 to become a little more solid.

**Comment by halocline** [comment]
> 2. I did run into these warnings. Storybook 7 dropped support for webpack 4, I think these warnings are coming from storybook dependencies and addons that still have some cleanup to do from moving to webpack 5. I didn't see anything that looked too concerning in the warnings, but if we want we can always wait a little longer to upgrade and give more time for storybook 7 to become a little more solid.

I agree with your assessment. I feel comfortable proceeding.

**Review by halocline — APPROVED** [review]

**Pull request merged**
