### PR TITLE
Remove use of `hoverIndicator` within Data

### PR DESCRIPTION
**Pull request by taysea**
#### What does this PR do?

According to button docs, `hoverIndicator` should only be used with `plain` Buttons. Removed improper use of `hoverIndicator` within Data components to allow theme to drive styling.

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
Related to https://github.com/grommet/grommet/pull/7069

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible, these components are still in beta.

### CODE REVIEW

**Review by jcfilben — COMMENTED** [review]
Looks like there are some snapshot issues when the tests run on circleci.

Also should we add the theme hover styling in this PR?

**Comment by taysea** [comment]
> Looks like there are some snapshot issues when the tests run on circleci.
> 
I'll resolve those.

> Also should we add the theme hover styling in this PR?

In base/grommet theme, icon only buttons don't have hover styling. In HPE theme, they will with the `toolbar` kind defined my HPE theme. So, I don't know that any theme changes are needed since it's behaving in accordance with the rest of grommet theme. What do you think?

**Comment by jcfilben** [comment]
> In base/grommet theme, icon only buttons don't have hover styling. In HPE theme, they will with the toolbar kind defined my HPE theme. So, I don't know that any theme changes are needed since it's behaving in accordance with the rest of grommet theme. What do you think?

Makes sense, agree I don't think we need theme changes then.

**Review by jcfilben — APPROVED** [review]
Looks good!

**Review by britt6612 — APPROVED** [review]

**Pull request merged**
