### PR TITLE
Upgrade styled components

### PR DESCRIPTION
**Pull request by jcfilben**
#### What does this PR do?
Upgrade to latest styled components version

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `asFragment()` is used for snapshot testing.

### CODE REVIEW

**Review by britt6612 — DISMISSED** [review]
all good on my end!

**Comment by britt6612** [comment]
Im getting the following:

● DateInput › format with date bounds

    thrown: "Warning: An update to %s inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act%s"

      at _getError (node_modules/jest-circus/build/utils.js:432:18)
          at Array.map (<anonymous>)

  ● DateInput › format with date bounds

    Uncaught 'Warning: An update to %s inside a test was not wrapped in act(...).\n' +
      '\n' +
      'When testing, code that causes React state updates should be wrapped into act(...):\n' +
      '\n' +
      'act(() => {\n' +
      '  /* fire events that update state */\n' +
      '});\n' +
      '/* assert on the output */\n' +
      '\n' +
      "This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act%s"

**Review by britt6612 — APPROVED** [review]

**Review by taysea — APPROVED** [review]
Tested on node 18 & 20. Looks good

**Comment by taysea** [comment]
The chromatic change is one that's been a bit flaky over recent dependency upgrades but from what i remember had to do with what chrome version chromatic is pulling in?

I'm okay with the change.

**Comment by jcfilben** [comment]
> The chromatic change is one that's been a bit flaky over recent dependency upgrades but from what i remember had to do with what chrome version chromatic is pulling in?

Yeah we've had the same issue with this snapshot in the past. I'm not remembering 100% but I know we looked into it and the chrome version problem sounds familiar

**Pull request merged**
