### PR TITLE
add support for border between in border array

### PR DESCRIPTION
**Pull request by hwdsjtu97**
#### What does this PR do?
Add support for using between border in border array props
#### Where should the reviewer start?
`Box.js`
#### What testing has been done on this PR?
`yarn test` passed
#### How should this be manually tested?
A storybook example added
#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
https://github.com/grommet/grommet/issues/6640
#### Screenshots (if appropriate)
image

#### Do the grommet docs need to be updated?
No
#### Is this change backwards compatible or is it a breaking change?
Compatible

### CODE REVIEW

**Comment by hwdsjtu97** [comment]
@ShimiSun

**Comment by hwdsjtu97** [comment]
@jcfilben

**Comment by jcfilben** [comment]
> @jcfilben Do you think that the refinement requests you listed should block this current PR? or can we file a separate issue to track it?

It looks like the changes requested already made their way into the PR. So no need to file a separate issue for this.

**Review by jcfilben — APPROVED** [review]
Looks good!

**Pull request merged**
