### PR TITLE
Add ability to type form component

### PR DESCRIPTION
**Pull request by mattoni**
Signed-off-by: Alexander Mattoni <5110855+mattoni@users.noreply.github.com>

#### What does this PR do?

This PR adds the ability to type Form components with the values expected.

```
// event.values is typed to InputTypes now.
<Form<InputTypes> onSubmit={event => console.log(event.values)} />
```

#### Where should the reviewer start?

`src/js/components/Form/index.d.ts`

#### What testing has been done on this PR?

Confirmed the prop types work on <Form> components, and that it works as it used to if not typed.

#### How should this be manually tested?

Create a <Form> component and type it with an interface of expected input values. Then, ensure onSubmit event.values is typed properly.

#### What are the relevant issues?

#4840 

#### Should this PR be mentioned in the release notes?

Probably

#### Is this change backwards compatible or is it a breaking change?
Backward compatible

### CODE REVIEW

**Comment by ericsoderberghp** [comment]
Thanks for working on this. If I understand it correctly, if seems like a good issue to resolve. I'm trying to ensure I've wrapped my head around it all. Does the example below seem like the right way to think of it with a bit more context?
```
interface FormValue {
  name?: string;
  email?: string;
}

const MyComponent = () => {
  const [value, setValue] = React.useState<FormValue>({ name: '', email: '' });
  return (
    <Form<FormValue> value={value} onSubmit={({ value: nextValue }) => setValue(nextValue)}>
      ...
    </Form>
  );
}
```
where the `value` prop of Form gets fully typed, instead of `{}` as it is today, and the `onSubmit` `event.value` gets fully typed as well. `value` and `setValue` are already fully typed via `useState<FormValue>`.

**Comment by mattoni** [comment]
@ericsoderberghp precisely! This allows us to make the form specific, and ensures type safety to all relevant properties.

**Comment by ericsoderberghp** [comment]
> @ericsoderberghp precisely! This allows us to make the form specific, and ensures type safety to all relevant properties.

Great. Thanks for clarifying. In that case, can we also amend the type of `value?` to be `T` instead of `{}`?

**Comment by ericsoderberghp** [comment]
Also, can we change the UncontrolledType story to do this, changing it from uncontrolled to controlled, to ensure all of the typings are handled correctly? I'm also thinking we wont need `FormExtendedEvent` inside that story anymore, as these changes should take care of it.

**Comment by mattoni** [comment]
Yes. In that case though, we should probably make the type of `T` default to `{}`  instead of `unknown` for backward compatibility.

**Comment by mattoni** [comment]
Sounds good, I'll try and get to that this week.

**Comment by ShimiSun** [comment]
@mattoni hi buddy, thanks for working on this PR, any updates on incorporating the feedback?

**Comment by mattoni** [comment]
Hi there, sorry I haven't had a chance yet but can look into it this week :)

**Comment by mattoni** [comment]
Sorry this took awhile to get to, had an unusually turbulent month! I think this is in-line with all the changes requested, but please let me know if there's anything else needed.

**Review by ericsoderberghp — APPROVED** [review]

**Comment by ericsoderberghp** [comment]
merged manually. Thanks for your contribution!

**Pull request closed without merging**
