### PR TITLE
fix/button dark mode color

### LINKED ISSUE #6301: Button - dark mode label color inconsistent
### Expected Behavior

If the theme doesn't specify a label color for a specific button state (e.g., active), then the active button should have the same label color as the default state.

### Actual Behavior

In dark mode, when a button's default state has a background with opacity < 1 (such as background-contrast) the label color is coming through differently than when that button is active.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/active-button-color-pmujf7?file=/index.js

### Steps to Reproduce

Notice the difference in color in the dark mode of the "test button" vs "active test button"

### Your Environment

- Grommet version: 2.25.1
- Browser Name and version: MacOS Chrome
- Operating System and version (desktop or mobile): MacOS Mojave

### PR DESCRIPTION
**Pull request by paola-machado**
#### What does this PR do?
Closes #6301 - "If the theme doesn't specify a label color for a specific button state (e.g., active), then the active button should have the same label color as the default state."

#### Where should the reviewer start?
On the Button component. `DarkMode.js` was added to the storybook for visual testing, and the file `StyledButtonKind.js` was modified, as well as the related snapshots.

#### What testing has been done on this PR?
Snapshot was fixed and all tests are passing. Also used Storybook.

#### How should this be manually tested?
`yarn test`

#### Do Jest tests follow these best practices?

- [ ] `screen` is used for querying.
- [ ] The correct query is used. (Refer to [this list of queries](https://testing-library.com/docs/queries/about/#priority))
- [ ] `userEvent` is used in place of `fireEvent`.
- [ ] `asFragment()` is used for snapshot testing.

#### What are the relevant issues?
#6301

#### Do the grommet docs need to be updated?
No

#### Should this PR be mentioned in the release notes?
No

#### Is this change backwards compatible or is it a breaking change?
Backwards compatible

### CODE REVIEW

**Comment by taysea** [comment]
Thanks for having a look at this @paola-machado ! I would expect that the active button with background contrast would receive #FFFFFF (text-strong) as the label color in your story as opposed to `text` (which is coming from the inherit.

**Comment by paola-machado** [comment]
Ops, I think I misunderstood the issue! Thank you for noticing @taysea, I'll take another look at this 👍🏻

**Comment by jcfilben** [comment]
Hey @paola-machado just wanted to check-in and see if you had any questions or were stuck anywhere on this PR, we're here to help if needed

**Comment by paola-machado** [comment]
> check-in and see if you had any questions or were stuck anywhere on this PR, we're here to help if needed

hiya! I had some personal issues that prevented me from looking into this again, but I'll return to it next week! If any questions arise I'll be sure to send them here! Thank you for your patience ♥

**Comment by jcfilben** [comment]
> hiya! I had some personal issues that prevented me from looking into this again, but I'll return to it next week! If any questions arise I'll be sure to send them here! Thank you for your patience ♥

No worries, totally understand! Just wanted to make sure you weren't stuck on this or anything

**Comment by jcfilben** [comment]
Closing due to inactivity, feel free to re-open

**Pull request closed without merging**
