### PR TITLE
fix long-label issue with radio and checkbox

### PR DESCRIPTION
**Pull request by dgennetten**
#### What does this PR do?
fix the long-label issue with CheckBox and Radio
#### Where should the reviewer start?
https://codepen.io/nickjvm/pen/EmvwBW?editors=0110
#### What testing has been done on this PR?
Edge, Chrome, IE, Safari
#### Any background context you want to provide?
this adds width, which is valid in combination with inline-block

### CODE REVIEW

**Comment by dgennetten** [comment]
Forgot to mention: this issue appears on IE/Edge/Chrome/Firefox but on PC-only!

**Comment by nickjvm** [comment]
@dgennetten for what it's worth, I was seeing it on OS X 10.11.6 with a 3rd-party mouse. (Scrollbars in OS X are hidden by default if you're using a magic mouse or touch pad)

**Comment by dgennetten** [comment]
@alansouzati I believe this is ready to merge.

**Comment by alansouzati** [comment]
let me review this. sorry for taking a long time to look into this.

**Comment by karatechops** [comment]
Whoops, looks like I overlapped this one with #1612. As this is a specific issue to compact Form would it make more sense to target the `--compact` modifier class within Form?

**Comment by karatechops** [comment]
@dgennetten we're you able to identify any issues with the labels outside of compact forms?

**Pull request closed without merging**
