### PR TITLE
Enable Box component gap prop to use css values

### PR DESCRIPTION
**Pull request by mirshko**
#### What does this PR do?

Enables the box gap prop to support just a css value as well

#### Where should the reviewer start?

Box component

#### What testing has been done on this PR?

None

#### How should this be manually tested?

Adding in gap with a pixel / css value

#### Any background context you want to provide?

Fixing a discrepancy with the docs

#### Do the grommet docs need to be updated?

Nope.

#### Is this change backwards compatible or is it a breaking change?

Backwards compatible :)

### CODE REVIEW

**Comment by oorestisime** [comment]
hey, this is looking good! 
I think there is already a unit-test covering the gap prop. would you mind altering it to cover this case as well?

**Comment by mirshko** [comment]
@oorestisime okay i think i got it!

**Comment by mirshko** [comment]
ran that!

**Comment by mirshko** [comment]
ahh it didn’t commit will finish up later

**Comment by ericsoderberghp** [comment]
Thanks for your contribution!

**Pull request merged**
