### PR TITLE
Changed Video to use hooks

### PR DESCRIPTION
**Pull request by ericsoderberghp**
#### What does this PR do?

Changed Video to use hooks

#### Where should the reviewer start?

Video.js

#### What testing has been done on this PR?

storybook + unit

#### How should this be manually tested?

storybook

#### Do the grommet docs need to be updated?

no

#### Should this PR be mentioned in the release notes?

yes

#### Is this change backwards compatible or is it a breaking change?

backwards compatible

### CODE REVIEW

**Comment by ShimiSun** [comment]
Looks great! 
A couple of thoughts: 
1. I've tried the deployment and I'm thinking we might need a higher zIndex for the control focus to make the bottom and left border pop better:
image
2. The focus for the scrubbing has a different style than the grommet focus
image
3. The video isn't playing so it's difficult to end to end test these changes.

**Comment by ericsoderberghp** [comment]
> The focus for the scrubbing has a different style than the grommet focus

No change from prior behavior. We can take care of this separately.

**Comment by ericsoderberghp** [comment]
> I've tried the deployment and I'm thinking we might need a higher zIndex for the control focus to make the bottom and left border pop better:

No change from prior behavior. We can take care of this separately.

**Comment by ericsoderberghp** [comment]
> The video isn't playing so it's difficult to end to end test these changes.

Hmm... it's working for me. Is the Meter/scrubber not advancing?

**Comment by ShimiSun** [comment]
This is what I see:
image

I ran your branch locally and it works as expected on dev mode, but if you'll look on the [Netlify deployment](https://deploy-preview-4061--sad-tereshkova-173d07.netlify.app/?path=/story/video--simple), there is no video attached to the example.

**Comment by ericsoderberghp** [comment]
> This is what I see:
> image
> 
> I ran your branch locally and it works as expected on dev mode, but if you'll look on the [Netlify deployment](https://deploy-preview-4061--sad-tereshkova-173d07.netlify.app/?path=/story/video--simple), there is no video attached to the example.

I think this is unrelated to these changes. On Chrome, the existing grommet video stories aren't working either: https://storybook.grommet.io/?path=/story/video--controls-below I think Chrome isn't handling the mixture or http and https.

**Pull request merged**
